.github/workflows/CD.yml
.github/workflows/CI.yml
build.gradle.kts

- close #1
- X
- CI.yml, CD.yml을 추가합니다.
- CI는 PR, push 될 때 테스트를 실행합니다.
- CD는 push된 코드로 도커 이미지를 생성해 aws 인스턴스에 배포합니다.
- deploy 스크립트는 ec2에 먼저 올리고, 배포가 확인되면 깃에 올리면 좋을 것 같아요

Feat: CI / CD 파이프라인 구축

---

src/main/java/com/dnd/runus/domain/example/ExampleController.java
src/main/java/com/dnd/runus/global/config/SwaggerConfig.java
src/main/java/com/dnd/runus/global/constant/TimeConstant.java
src/main/java/com/dnd/runus/presentation/config/ObjectMapperConfig.java

- close #26 
- X
- `ObjectMapperConfig`에서 아래 클래스의 직렬화 형식을 지정합니다.
- LocalTime -> `HH:mm:ss`
- LocalDate -> `yyyy-MM-dd`
- LocalDateTime -> `yyyy-MM-dd HH:mm:ss`
- OffsetDateTime -> `yyyy-MM-dd HH:mm:ss`
- Instant -> `yyyy-MM-dd HH:mm:ss`
- 스웨거에서 확인했어요

Feat: time format 설정

---

src/main/java/com/dnd/runus/presentation/config/ObjectMapperConfig.java

- #26 
- X
- `LocalDateTime`을 `yyyy-MM-dd` 형식으로 파싱하도록 합니다.
- LocalDate나 LocalTime을 지금 포멧에서는 따로 설정할 필요 없습니다.
-

Feat: LocalDateTime 역직렬화 추가

---

src/main/resources/application.yml

- #34 
- X
- yml 파일 postgis database-platform deprecated 이슈로 `org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect` 에서 `org.hibernate.dialect.PostgreSQLDialect`로 변경
- X

Fix: postgis database-platform deprecated 제거

---

src/main/java/com/dnd/runus/infrastructure/persistence/jpa/running/entity/RunningRecordEntity.java
src/main/resources/db/migration/V3__alter_running_record_route_type.sql

- #30
- X
- https://github.com/dnd-side-project/dnd-11th-2-backend/issues/30#issuecomment-2271410751 에서 논의한 사항을 적용합니다.
- `RunningRecord` `route` 컬럼의 데이터베이스 type을 `LineStringZ`로 변경해요
-

Fix: RunningRecord route db type을 LineStringZ로 변경

---

src/main/java/com/dnd/runus/domain/running/RunningRecordRepository.java
src/main/java/com/dnd/runus/infrastructure/persistence/domain/running/RunningRecordRepositoryImpl.java
src/main/java/com/dnd/runus/infrastructure/persistence/jpa/running/JpaRunningRecordRepository.java
src/test/java/com/dnd/runus/infrastructure/persistence/domain/running/RunningRecordRepositoryImplTest.java

- #40 
- #50 
- X
- 러닝 기록 멤버id로 삭제합니다.
-

Feat: 러닝 기록 멤버id로 삭제 구현

---

src/main/java/com/dnd/runus/auth/oidc/provider/impl/AppleAuthProvider.java

- X
- X
- 클라이언트 테스트를 위한 nonce 체크 주석처리
- X

Fix: 테스트를 위한 주석 처리

---

src/main/java/com/dnd/runus/auth/oidc/provider/impl/AppleAuthProvider.java

- #55
- X
- java- jar로 실행 시 File로 파일을 읽어오지 못하는 오류를 수정합니다.
- InputStream을 사용해서 파일을 읽어옮니다.
- X

Fix: 스테이징 서버에서 실행 시 파일이 존재하지 않음 오류수정

---

.gitignore
src/main/java/com/dnd/runus/auth/oidc/provider/impl/AppleAuthProvider.java

- #63 
- X
- 클래스패스에 app디렉토리가 존재 안 해서 마운팅 안되는 것 같습니다.
-  resources/app/apple 빈 디렉토리 추적을 위해  resources/app/apple 에 .gitkepp 파일을 추가합니다.
-

Fix: docker compose에서 Class Path 디렉토리로 마운팅할 수 없는 오류 수정

---

src/main/java/com/dnd/runus/domain/level/Level.java
src/main/java/com/dnd/runus/infrastructure/persistence/jpa/level/entity/LevelEntity.java
src/main/resources/db/migration/V5.0.0__add_level_image.sql
src/test/java/com/dnd/runus/infrastructure/persistence/domain/member/MemberLevelRepositoryImplTest.java

- close #66 
- X
- Level 이미지 컬럼을 추가합니다.
- S3 버킷 추가해두었어요!

Feat: level image_url 컬럼 추가

---

src/main/java/com/dnd/runus/application/oauth/OauthService.java
src/main/java/com/dnd/runus/domain/member/MemberLevel.java

- #3 
- X
- 회원가입시 멤버 레벨 초기값(레벨 1, exp:0)을 insert 합니다.
-

Feat: 회원가입 시 memberLevel insert 추가

---

src/main/java/com/dnd/runus/application/challenge/ChallengeService.java
src/main/java/com/dnd/runus/domain/challenge/achievement/ChallengeAchievementRepository.java
src/main/java/com/dnd/runus/infrastructure/persistence/domain/challenge/ChallengeAchievementRepositoryImpl.java
src/main/java/com/dnd/runus/infrastructure/persistence/jpa/challenge/JpaChallengeAchievementRepository.java
src/test/java/com/dnd/runus/application/challenge/ChallengeServiceTest.java
src/test/java/com/dnd/runus/infrastructure/persistence/domain/challenge/ChallengeAchievementRepositoryImplTest.java

- #72 
- X
- 사용자 챌린지 성취 기록을 조회합니다.
-

Feat: 사용자 챌린지 달성 조회

---

src/main/java/com/dnd/runus/global/constant/WeatherType.java
src/main/java/com/dnd/runus/infrastructure/weather/WeatherClient.java
src/main/java/com/dnd/runus/infrastructure/weather/WeatherInfo.java
src/main/java/com/dnd/runus/infrastructure/weather/mock/MockWeatherClient.java

- #105 
- X
- `WeatherClient` 인터페이스를 추가합니다.
- `MockWeatherClient`를 추가합니다.
- 9가지 날씨 종류를 나타내는 `WeatherType`를 추가합니다.
-

Feat: weather client 추가

---

gradle/libs.versions.toml
src/main/java/com/dnd/runus/global/exception/type/ErrorType.java
src/main/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherClient.java
src/main/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherHttpClient.java
src/main/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherHttpClientConfig.java
src/main/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherInfo.java
src/main/resources/application.yml
src/test/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherHttpClientTest.java
src/test/resources/application.yml

- close #105 
- X
- https://openweathermap.org/current API를 사용합니다.
- http client 테스트를 위해 Wiremock을 사용합니다.
-

Feat: openweathermap client 추가

---

src/main/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherClient.java
src/main/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherHttpClient.java
src/main/java/com/dnd/runus/presentation/v1/weather/WeatherController.java
src/test/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherHttpClientTest.java

- close #121 
- X
- weather openweathermap에서 401에러가 발생하지 않도록 수정합니다.
-

Fix: weather openweathermap api 요청시 request param에 appid를 포함하도록 수정

---

src/main/java/com/dnd/runus/application/running/RunningRecordService.java

- #90
- 
- 인식하지 못하는 ZoneOffset 대신 defaultZoneOffset을 사용하도록 합니다.
-

Fix: 인식하지 못하는 ZoneOffset 대신 defaultZoneOffset을 사용하도록 수정

---

src/main/java/com/dnd/runus/presentation/v1/running/RunningRecordController.java
src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordAddResultResponse.java
src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordMonthlyDatesResponse.java
src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordSummaryResponse.java

- close #120 
- X
- `api/v1/running-record/**` API 중 Request, Resposne 필드에 예제가 빠진 경우를 보충합니다.
-

Docs: running record api docs 필드 example 추가

---

src/main/java/com/dnd/runus/global/constant/WeatherType.java

- close #124 
- X
- `WeatherType` 기존의 임시 문구를 정해진 문장으로 수정합니다.
-

Fix: 기존의 임시 weather 문구를 정해진 문장으로 수정

---

src/main/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherClient.java
src/main/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherHttpClient.java
src/main/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherHttpClientConfig.java
src/test/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherHttpClientTest.java

- close #128 
- X
- openweathermap api 요청시 단위를 켈빈온도에서 섭씨온도로 변경합니다.
-

Fix: openweathermap api 요청시 단위를 켈빈온도에서 섭씨온도로 변경

---

src/main/java/com/dnd/runus/presentation/v1/server/ServerController.java
src/main/java/com/dnd/runus/presentation/v1/server/dto/response/VersionStatusResponse.java

- #142 
- GET `api/v1/servers/versions`: 앱 버전 확인 API
- 앱 버전을 확인해 업데이트해야 할지를 반환하는 API를 추가합니다.
- 빠른 구현을 위해 현재로선 업데이트를 하지 않아도 된다고 고정해두었어요.

Feat: app version 확인 API 추가

---

src/main/java/com/dnd/runus/presentation/config/SecurityWebConfig.java

- #142 
- X
- GET `api/v1/servers/versions`를 인증하지 않아도 사용할 수 있도록 변경합니다.
-

Feat: app version 확인 API 인증 없이 사용할 수 있게 수정

---

src/main/java/com/dnd/runus/domain/scale/Scale.java
src/main/java/com/dnd/runus/infrastructure/persistence/jpa/scale/entity/ScaleEntity.java
src/main/resources/db/migration/V5.0.12__add_scale_from_to_column.sql
src/test/java/com/dnd/runus/infrastructure/persistence/domain/scale/ScaleRepositoryImplTest.java

- #149
- X
- 해당 커밋을 revert합니다.
- 0e8bc560c5b770609b477a5c145ac439dbf78ccc.
- #150

Revert: scale 테이블에 달성 목표 값을 나타내는 achievement_value_meter컬럼 추가

---

build.gradle.kts
gradle/libs.versions.toml

- X
- X
- 컴파일 시 발생하는 `unknown enum constant When.MAYBE` warning이 발생하여 해당 경고를 제거합니다.
- 해당 warning은 `@Nullable` 이 열거형을 사용하는데 자동으로 사용하도록 되어있지 않아서 발생하는 warning입니다.
- 해당 경고를 제거하기 위해 dependcies에 [findbugs](https://github.com/findbugsproject/findbugs)를 추가 합니다.
-

Fix : 컴파일 시 발생하는 unknown enum constant When.MAYBE 경고 제거

---

README.md

- x
- x
- 메인 readme 파일을 추가합니다.
- 보시고 아무 의견이나 주세요! (순서, 요소 추가 삭제 등)

Docs: readme 내용 추가

---

.github/workflows/CI.yml

- close #183 
- X
- 로컬에서 테스트 진행 시 성공하지만, github ci로 진행 시 Fail되는 문제를 파악하기 위해 테스트 결과를 아티팩트로 업로드하는 단계를 ci에 추가합니다.
- 실패할 경우에만 아티팩트를 생성합니다.
-

Feat: CI upload-artifact 추가

---

src/main/java/com/dnd/runus/domain/running/RunningRecordRepository.java
src/main/java/com/dnd/runus/infrastructure/persistence/domain/running/RunningRecordRepositoryImpl.java
src/main/java/com/dnd/runus/infrastructure/persistence/jooq/running/JooqRunningRecordRepository.java
src/test/java/com/dnd/runus/infrastructure/persistence/domain/running/RunningRecordRepositoryImplTest.java

- #180 
- X
- 기간 내 달린 평균 거리 값을 조회하는 함수를 Repository에 추가합니다.
- 기간 내 달린 평균 시간 값을 조회하는 함수를 Repository에 추가합니다.
-

Feat: 러닝 데이터의 평균 값을 구하는 함수를 Repository에 추가

---

build.gradle.kts
gradle/libs.versions.toml
src/main/java/com/dnd/runus/global/constant/CacheType.java
src/main/java/com/dnd/runus/infrastructure/cache/CacheConfig.java

- close #186
- X
- cache 라이브러리로 caffeine 3.1.8을 사용합니다.
- `CacheType`에 필요한 캐시 종류들을 추가하시면 돼요!

Chore: caffeine cache 추가

---

src/main/java/com/dnd/runus/application/scale/ScaleService.java
src/main/java/com/dnd/runus/domain/challenge/Challenge.java
src/main/java/com/dnd/runus/domain/common/Pace.java
src/main/java/com/dnd/runus/domain/goalAchievement/GoalAchievement.java
src/main/java/com/dnd/runus/domain/level/Level.java
src/main/java/com/dnd/runus/global/constant/MetricsConversionFactor.java
src/main/java/com/dnd/runus/presentation/config/ObjectMapperConfig.java
src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordMonthlySummaryResponse.java
src/main/java/com/dnd/runus/presentation/v1/scale/dto/ScaleCoursesResponse.java

- close #199 
- X
- 거리, 시간 관련 변환 값을 `MetricsConversionFactor`의 constant값으로 변경 합니다.
-

Refactor: 거리, 시간 관련 변환 값을 constant값으로 변경

---

src/main/java/com/dnd/runus/presentation/config/SecurityWebConfig.java
src/main/resources/application.yml

- close #210 
- x
- actuator health, metrics api 경로에 대해 http get 메서드 접근을 허용합니다.
-

Feat: spring actuator health, metrics api 허용

---

build.gradle.kts
gradle/libs.versions.toml
src/main/resources/application.yml

- close #217 
- x
- Prometheus 의존성을 추가합니다.
-

Chore: Prometheus 의존성 추가

---

src/main/java/com/dnd/runus/presentation/config/SecurityWebConfig.java

- x
- x
- spring actuator의 prometheus url에 접근 가능하도록 수정합니다.
-

Fix: prometheus url 허용으로 수정

---

README.md

- x
- x
- 배포 구조 이미지를 변경합니다.
- 제목에 번호를 매깁니다.
-

Docs: readme 배포 구조 이미지 최신화

---

.github/workflows/CD.yml
.github/workflows/CI.yml
README.md
build.gradle.kts
gradle/libs.versions.toml

- close #223 
- x
- Java 17에서 버전 21로 마이그레이션합니다.
- Spring Boot 버전을 `3.3.2`에서 `3.3.4`로 patch 버전을 변경합니다.
-

Chore: java 17에서 21로 버전 마이그레이션

---

.github/workflows/CD.yml

- #234 
- X
- Blue-Green 배포을 위해 `docker-compose.app.yml` 파일을 `docker-compose.blue.yml`, `docker-compose.green.yml`로 분리합니다.
-  Blue-Green 배포을 위한 배포 스크립트를 운영 서버에 추가합니다.
- 기존에 스크립트가 있었던 디렉토리에 `scripts` 디렉토리를 추가해 해당 디렉토리에 배포 스크립트를 추가합니다.
- 배포 스크립트의 위치 변경으로 CD 파일을 수정합니다.
-

Feat: Blue-Green 배포 구현

---

src/main/java/com/dnd/runus/application/config/AsyncConfig.java

- close #229 
- x
- virtual thread 사용한 AsyncConfig 클래스를 추가합니다.
- `getAsyncUncaughtExceptionHandler`를 상속받아 예외 발생 시 로그를 남기도록 했습니다.
- Exception 이름, 메세지, 메서드 이름, 파라미터 값들
-

Feat: virtual thread 사용한 AsyncConfig 추가

---

src/main/java/com/dnd/runus/infrastructure/persistence/jooq/JooqConfig.java

- #198 
- x
- 불필요한 jOOQ 로고와 tips 출력을 끄도록 변경합니다.
- 아래는 출력된 결과입니다.
```
2024-09-27T18:16:10.637+09:00  INFO 1 --- [run-us] [nio-8080-exec-5] org.jooq.Constants                       :
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@  @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@        @@@@@@@@@@
@@@@@@@@@@@@@@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@  @@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@        @@  @  @  @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@  @@@@@@@@@@@@@ …
```

Feat: jOOQ tips와 logo 출력문 삭제

---

src/main/resources/application.yml

- x
- x
- 기존에는 Grafana 대시보드에 Jetty 정보가 있지만 Tomcat 관련 정보가 없습니다.
- Tomcat에 대한 지표를 수집할 수 있도록 `application.yml`의 tomcat 관련 메트릭을 활성화합니다.
-

Feat: application.yml에서 tomcat metrics 활성화

---

src/main/resources/application.yml

- #198 
- #241 
- x
- #241 에서 prod 환경 로그 레벨이 잘못 설정된 점을 수정합니다.
- prod 환경에서 Hibernate DEBUG, TRACE 레벨 로그가 출력되지 않도록 수정합니다.
-

Fix: Hibernate prod 로그 레벨 수정

---

src/main/java/com/dnd/runus/domain/challenge/achievement/ChallengeAchievement.java
src/main/java/com/dnd/runus/infrastructure/persistence/jpa/challenge/entity/ChallengeAchievementEntity.java
src/test/java/com/dnd/runus/infrastructure/persistence/domain/challenge/ChallengeAchievementPercentageRepositoryImplTest.java
src/test/java/com/dnd/runus/infrastructure/persistence/domain/challenge/ChallengeAchievementRepositoryImplTest.java

- x
- x
- ChallengeAchievement의 id 필드를 카멜 케이스로 수정로 수정합니다.
-

Style: ChallengeAchievement의 id 필드를 카멜 케이스로 수정

---

README.md

- x
- x
- 앱스토어 배포 링크를 추가합니다.
- <a href="https://apps.apple.com/kr/app/runus/id6689522964" target="_blank"> <img src="https://github.com/user-attachments/assets/cfb6c288-7b66-4488-98c7-df07de27e8a5" alt="Download_on_the_App_Store_Badge" width="150"></a>
-

Docs: readme 앱스토어 배포 링크 추가

---

src/main/java/com/dnd/runus/presentation/config/SwaggerConfig.java

- api 버전 관리로 API문서에 버전 별 그룹을 추가합니다.
-

Docs: SwaggerConfig에 api 버전 그룹 추가

---

src/main/java/com/dnd/runus/application/running/RunningRecordService.java
src/main/java/com/dnd/runus/domain/common/CoordinatePoint.java
src/main/java/com/dnd/runus/domain/running/RunningRecord.java
src/main/java/com/dnd/runus/infrastructure/persistence/domain/GeometryMapper.java
src/test/java/com/dnd/runus/application/challenge/ChallengeServiceTest.java
src/test/java/com/dnd/runus/application/member/MemberWithdrawServiceTest.java
src/test/java/com/dnd/runus/application/running/RunningRecordServiceTest.java
src/test/java/com/dnd/runus/infrastructure/persistence/domain/challenge/ChallengeAchievementPercentageRepositoryImplTest.java
src/test/java/com/dnd/runus/infrastructure/persistence/domain/challenge/ChallengeAchievementRepositoryImplTest.java
src/test/java/com/dnd/runus/infrastructure/persistence/domain/goalAchievement/GoalAchievementRepositoryImplTest.java
src/test/java/com/dnd/runus/infrastructure/persistence/domain/running/RunningRecordRepositoryImplTest.java
src/test/java/com/dnd/runus/infrastructure/persistence/domain/scale/ScaleRepositoryImplTest.java
src/test/java/com/dnd/runus/infrastructure/persistence/jpa/running/entity/RunningRecordEntityTest.java

…inatePoint로 변경
- #319 
- X
- `org.locationtech.jts.geom`라이브러리의 `Coordinate`와의 혼동을 방지와 가독성을 위해 `com.dnd.runus.domain.common` 패키지의 Coordinate 클래스 명을 CoordinatePoint으로 변경합니다.
-

Rename: Coordinate 클래스 명을 CoordinatePoint로 변경
