dnd-side-project/dnd-11th-2-backend

.github/workflows/CI.yml, build.gradle.kts, scripts/pre-commit.sh, src/test/java/com/dnd/runus/RunUsApplicationTests.java
- close #4 
- X
- spotless 플러그인을 추가합니다.
- 스프링 프로그램을 실행하거나, `./gradlew compileJava`를 실행하면 사용할 준비가 끝납니다.
- 이후에는 git에 staged된 파일들을 커밋할 경우, 자동으로 palantir 스타일을 적용합니다.
- palantir import순서보단 인텔리제이 import 순서와 동일하게 합니다.
- 임의 import, java, static 순서
- 스타일을 체크하도록 테스트하는 `projectTest` gradle task를 추가합니다.
- 매번 `./gradlew spotlessApply`를 실행시키면 귀찮을 것 같아서,
git pre commit 스크립트로 자동화하도록 했어요.
그래서 커밋할때 살짝 버벅이는 것 같은데, 이 부분이 괜찮을까요?
=> Chore: spotless 플러그인 추가

build.gradle.kts, src/main/java/com/dnd/runus/global/config/SwaggerConfig.java, src/main/resources/application.yml
- close #8
- X
- Swagger 문서화 설정을 추가합니다.
- Swagger `pageable` 기본 설정 대신, 입력하기 쉬운 param 형태를 사용합니다.
- 스프링 기본 프로필을 `local`로 수정합니다.
- 서버를 실행한 뒤, 아래 주소로 접속하면 확인하실 수 있어요!
- http://localhost:8080/swagger-ui/index.html
=> Feat: Swagger 설정 추가

build.gradle.kts, src/main/java/com/dnd/runus/domain/common/BaseTimeEntity.java, src/main/java/com/dnd/runus/domain/member/entity/Member.java, src/main/java/com/dnd/runus/domain/member/repository/MemberRepository.java, src/main/java/com/dnd/runus/global/config/JpaConfig.java, src/main/java/com/dnd/runus/global/constant/MemberRole.java, src/main/java/com/dnd/runus/global/constant/SocialType.java
- close #11 
- X
- `Member` 엔티티 클래스를 추가합니다.
- `createdAt`, `updatedAt` 필드는 auditing 되도록 설정합니다.
- Annotation 관련 포메팅을 수정합니다. (한줄로 압축 -> 여러줄 유지)
- `Member` 엔티티에 `nickname`은 아직 넣지 않았는데, 피그마 보니 필요할 것 같아요.
=> Feat: member 엔티티 추가

build.gradle.kts
- #9 
- X
- WAS 버전은 docker image tag에서 가져오도록 수정합니다.
- 스웨거 접속시, image tag를 version 항목에서 확인할 수 있습니다.
-
=> Fix: imageName에서 version을 가져오도록 수정

build.gradle.kts, scripts/pre-commit.sh
- #4
- x
- `chmod` 대신 `file.setExecutable()`를 사용홥니다.
- `pre-commit.sh`에 OS에 따라 다르게 처리합니다.
- 안되면 말씀해주세요!
=> Fix: windows 환경에서도 포메팅 스크립트가 실행하도록 수정

src/main/java/com/dnd/runus/global/config/SwaggerConfig.java, src/main/java/com/dnd/runus/global/exception/BaseException.java, src/main/java/com/dnd/runus/global/exception/BusinessException.java, src/main/java/com/dnd/runus/global/exception/NotFoundException.java, src/main/java/com/dnd/runus/global/exception/type/ApiErrorType.java, src/main/java/com/dnd/runus/global/exception/type/ErrorType.java, src/main/java/com/dnd/runus/presentation/config/ObjectMapperConfig.java, src/main/java/com/dnd/runus/presentation/config/WebConfig.java, src/main/java/com/dnd/runus/presentation/dto/response/ApiErrorDto.java, src/main/java/com/dnd/runus/presentation/dto/response/ApiResponse.java, src/main/java/com/dnd/runus/presentation/handler/ApiResponseHandler.java, src/main/java/com/dnd/runus/presentation/handler/ExceptionRestHandler.java, src/main/java/com/dnd/runus/presentation/handler/NullResponseHandler.java
- close #15 
- X
- 데일리 스크럼에서 결정된 API 반환 형식으로 반환하도록 설정합니다.
```jsonc
{
"success": Bool,
"data": { // 데이터가 없는 경우에는 "data": {}
},
"error":  { // 에러 발생시 아래 필드는 필수
"statusCode": 000
"code": "...",
"message": ",,,"
}
}
```
- 성공인 경우, `error` 필드는 없앨 수 있다면 없도록 직렬화 합니다.
```jsonc
{
"success": true,
"data": {} // 보낼 데이터가 없는 경우라도 무조건 "data" 필드 보내기
}
```
```jsonc
{
"success": false,
"error": {
"statusCode": 400,
"code": "AUTH_001",
"message": "token is invalid 또는 token is empty.." // 디버깅 용도, 사용자 X
}
}
```
- 새로운 에러 형식이 필요하다면, `ErrorType` enum 클래스에 추가하시면 좋을 것 같아요!
=> Feat: API 공통 핸들러 추가

src/main/java/com/dnd/runus/domain/example/ExampleController.java
- #19
- GET `/api/v1/examples/pagination`: 페이징 확인
- GET `/api/v1/examples/data`: data 필드내 json 데이터 확인
- GET `/api/v1/examples/input`: request param 확인
- GET `/api/v1/examples/empty`: 빈 응답 확인
- GET `/api/v1/examples/errors`: 에러 발생 확인
- iOS팀에서 필요로 하는 간단한 테스트 용도의 컨트롤러를 추가합니다.
- 추후 삭제해야 합니다.
-
=> Feat: example controller 추가

src/main/java/com/dnd/runus/domain/badge/entity/Badge.java, src/main/java/com/dnd/runus/domain/badge/entity/BadgeAchievement.java, src/main/java/com/dnd/runus/domain/level/entity/Level.java, src/main/java/com/dnd/runus/domain/member/entity/Member.java, src/main/java/com/dnd/runus/domain/member/entity/PersonalProfile.java, src/main/java/com/dnd/runus/domain/member/entity/SocialProfile.java, src/main/java/com/dnd/runus/global/constant/BadgeType.java
- #14 
- X
아래 엔티티 클래스를 추가합니다.
- Badge
- BadgeAchievement: 멤버가 배지 달성 여부
- Level: 레벨 이름과 최소 경험치 요구량
기존 Member 엔티티 클래스를 수정합니다.
- Social, Personal profile 추가
- member 생성시 인자를 줄이기 위해서 social, personal로 관련있는 컬럼끼리 `@Embeddable`로 구분해두었습니다.
- `Level` id 키를 member에 저장하면 Level이 없어지면 사용자에게 보여줄 level이 없는게 이상해서 `exp` 경험치 컬럼을 member에 추가했습니다.
- 외래키로 저장해도 되지만, 경험치를 늘릴 때마다 다음 레벨인지 확인하고 업데이트할 필요가 없을 것 같아서 exp 컬럼을 두었습니다.
- 조회할 때는 exp에 맞는 level을 조회하면 어떨까요?
- `BadgeAchievement` 배지 달성 여부를 저장하는 테이블인데, badge, member는 둘다 외래키로 묶어 어느 하나가 삭제되면 해당 배재 달성 row로 삭제하면 좋을까요?
- apple 로그인 구현에 사용자 토큰 정보가 필요하다면, 이는 어디에 저장하면 좋을지 정하면 좋을 것 같아요
=> Feat: member profile, badge 엔티티 추가

build.gradle.kts, src/main/java/com/dnd/runus/domain/badge/entity/Badge.java, src/main/java/com/dnd/runus/domain/badge/entity/BadgeAchievement.java, src/main/java/com/dnd/runus/domain/level/entity/Level.java, src/main/java/com/dnd/runus/domain/member/entity/Member.java, src/main/java/com/dnd/runus/domain/member/entity/MemberLevel.java, src/main/java/com/dnd/runus/domain/member/entity/PersonalProfile.java, src/main/java/com/dnd/runus/domain/member/entity/SocialProfile.java, src/main/java/com/dnd/runus/domain/runing/entity/RunningEmoji.java, src/main/java/com/dnd/runus/domain/runing/entity/RunningRecord.java, src/main/java/com/dnd/runus/domain/runing/repository/RunningEmojiRepository.java, src/main/java/com/dnd/runus/domain/runing/repository/RunningRecordRepository.java, src/main/java/com/dnd/runus/global/constant/BadgeType.java, src/main/resources/application.yml
- close #14 
- X
- JPA 엔티티 클래스들을 추가합니다.
- erd 설계가 잘 되었는지 궁금합니다.
- 나머지는 댓글로 달겠습니다!
=> 설계한 ERD롤 토대로 JPA 엔티티 클래스들을 추가

src/main/java/com/dnd/runus/presentation/annotation/MemberId.java, src/main/java/com/dnd/runus/presentation/config/WebConfig.java, src/main/java/com/dnd/runus/presentation/resolver/MemberIdResolver.java
- close #31 
- X
- `MemberIdResolver`를 추가합니다.
- controller 계층에서 다음과 같이 사용할 수 있습니다.
- Security 계층에서 id 값을 가져와 memberId 변수에 넣으므로, 토큰을 사용하는(보호된) API 경로에서만 사용해야 합니다.
```java
@GetMapping
public void getMemberId(@MemberId long memberId) { ... }
```
=> Feat: member id resolver 추가

build.gradle.kts, src/test/java/com/dnd/runus/RunUsApplicationTests.java, src/test/java/com/dnd/runus/annotation/IntegrationTest.java, src/test/java/com/dnd/runus/config/TestcontainersConfig.java, src/test/resources/application.yml
- close #37 
- X
- testcontainers에서 postgis 확장 타입을 사용할 수 없던 점을 고칩니다.
- `@SpringBootTest` 대신 `@IntegrationTest`을 사용해주세요 !!
=> Fix: testcontainers postgis 이미지 설정 config 클래스 추가

src/main/java/com/dnd/runus/domain/oauth/dto/response/TokenResponse.java
- 로그인 후 grantType 반환 안함
- #3 
- X
- TokenResponse의 grantType 삭제합니다.
-
=> Fix: TokenResponse grantType 삭제

src/main/java/com/dnd/runus/infrastructure/persistence/jpa/badge/entity/BadgeAchievementEntity.java, src/main/java/com/dnd/runus/infrastructure/persistence/jpa/running/entity/RunningRecordEntity.java, src/main/resources/application.yml, src/test/resources/application.yml
- #41
- X
- 컬럼명에서 `entity`를 제거합니다. (SQL말고 JPA 엔티티 컬럼명에 잘못 entity를 적은 컬럼을 수정합니다)
- `ddl-auto` 속성을 `none`에서 `validate`로 변경합니다.
아래 글에 잘 설명되어 있으니 참고해주세요!
- https://stackoverflow.com/questions/42135114/how-does-spring-jpa-hibernate-ddl-auto-property-exactly-work-in-spring
> validate – Hibernate는 테이블과 칼럼이 존재하는지 여부만을 검증하고, 그렇지 않으면 예외를 발생시킨다
none – 이 값은 DDL 생성을 해제합니다.
=> Fix: ddl-auto validate 속성으로 변경

src/main/java/com/dnd/runus/domain/common/Coordinate.java, src/main/java/com/dnd/runus/domain/common/Pace.java, src/main/java/com/dnd/runus/domain/running/RunningRecord.java, src/main/java/com/dnd/runus/global/exception/NotFoundException.java, src/main/java/com/dnd/runus/infrastructure/persistence/domain/GeometryMapper.java, src/main/java/com/dnd/runus/infrastructure/persistence/jpa/running/entity/RunningRecordEntity.java, src/main/resources/db/migration/V2__alter_running_record_avg_pace.sql, src/test/java/com/dnd/runus/infrastructure/persistence/jpa/running/entity/RunningRecordEntityTest.java
- #30 
- X
- Pace 클래스를 추가합니다.
- `running_record` 테이블의 컬럼을 수정합니다.
-  pace 컬럼을 double -> integer (minute * 60 + second)로 저장합니다.
- `RunningRecordEntity`의 pace 필드 타입을 Double -> Integer로 수정합니다.
- `RunningRecord`
- pace를 double 대신 Pace 클래스를 사용합니다.
- durationSeconds (integer)를 Duration 타입으로 변경합니다.
- Pace를 저장할때, double 대신 integer(분 * 60 + 초)로 저장하면 비교하기 더 편할 것 같은데 어떠신가요?
- 배지 부여를 할때, 평균 페이스도 일정 수치에 따라 기준을 정해야 하는데,
badge 테이블의 requred_value 컬럼이 integer로 되어 있어서, pace 저장할 때도 integer 타입을 사용하면 좋을 것 같아요
=> Fix: running record 테이블 pace 컬럼 타입을 정수형으로 변경

src/main/java/com/dnd/runus/domain/common/Pace.java, src/test/java/com/dnd/runus/domain/common/PaceTest.java
- #30
- X
- `"` 대신 `''`을 사용해요
- json body에 `"`을 사용하지 못해요
- `\"`으로 보내니 \도 같이 그대로 인식해요
- 그래서 `"` 대신 `'` 2개를 사용하도록 변경해요
- 관련 테스트도 추가했으니 확인 부탁드려요!
=> Fix: Pace json format 형식에서 "대신 ''을 사용하도록 수정

src/main/resources/db/migration/V4__fix_member_level_fk.sql
- close #53 
- X
- 기존에는 `references member_level references member`로 적혀 있습니다.
- references는 한 번만 적어야 하므로, `member_level` 테이블의 FK를 올바르게 수정합니다.
-
=> Fix: member_level table member_id fk 오류 수정

src/main/java/com/dnd/runus/auth/oidc/provider/impl/AppleAuthProvider.java
- #57 
- X
- 애플의 가이드 라인에 따라 애플 사용자의 검증 과정을 추가합니다.
-
=> Feat: 애플 사용자 검증 구현

src/main/java/com/dnd/runus/application/running/RunningRecordService.java, src/main/java/com/dnd/runus/domain/level/LevelRepository.java, src/main/java/com/dnd/runus/domain/member/MemberLevel.java, src/main/java/com/dnd/runus/domain/member/MemberLevelRepository.java, src/main/java/com/dnd/runus/infrastructure/persistence/domain/level/LevelRepositoryImpl.java, src/main/java/com/dnd/runus/infrastructure/persistence/domain/member/MemberLevelRepositoryImpl.java, src/main/java/com/dnd/runus/infrastructure/persistence/jooq/member/JooqMemberLevelRepository.java, src/main/java/com/dnd/runus/infrastructure/persistence/jpa/level/JpaLevelRepository.java, src/main/java/com/dnd/runus/infrastructure/persistence/jpa/level/entity/LevelEntity.java, src/main/java/com/dnd/runus/infrastructure/persistence/jpa/member/JpaMemberLevelRepository.java, src/main/java/com/dnd/runus/infrastructure/persistence/jpa/member/entity/MemberLevelEntity.java, src/test/java/com/dnd/runus/application/running/RunningRecordServiceTest.java, src/test/java/com/dnd/runus/config/TestJooqConfig.java, src/test/java/com/dnd/runus/infrastructure/persistence/annotation/RepositoryTest.java, src/test/java/com/dnd/runus/infrastructure/persistence/domain/member/MemberLevelRepositoryImplTest.java
- close #65 
- X
- 러닝을 저장할때, 사용자의 레벨을 같이 업데이트합니다.
- 추가되는 경험치는 meter 단위로 추가해요
- 경험치에 해당하는 레벨이 없는 경우, level table에서 id를 찾지 못해서 NPE가 발생해요
- 경험치가 int max를 넘어가지 않는지 확인해야 해요
- 2,147,483km를 달려야 하는데(지구가 46,000km), 사용자가 조작하지 않는 이상 불가능해요
=> Feat: member 레벨업 기능 추가

src/main/java/com/dnd/runus/application/oauth/OauthService.java, src/main/java/com/dnd/runus/auth/oidc/provider/OidcProvider.java, src/main/java/com/dnd/runus/presentation/v1/oauth/OauthController.java, src/main/java/com/dnd/runus/presentation/v1/oauth/dto/request/WithdrawRequest.java
- #70 
- 회원 탈퇴 api를 추가합니다.
- X
-
=> Docs: 회원 탈퇴 api 문서

src/main/java/com/dnd/runus/domain/member/MemberLevel.java, src/main/java/com/dnd/runus/domain/member/MemberLevelRepository.java, src/main/java/com/dnd/runus/infrastructure/persistence/domain/member/MemberLevelRepositoryImpl.java, src/main/java/com/dnd/runus/infrastructure/persistence/jooq/member/JooqMemberLevelRepository.java, src/test/java/com/dnd/runus/infrastructure/persistence/domain/member/MemberLevelRepositoryImplTest.java
- #65 
- X
- 레벨 업하고 나서 레벨 조회를 하지 않으므로, `UPDATE .. RETURNING` SQL 절을 삭제합니다.
- 전에 언급하신 사항인데, `memberLevelId`로 잘못 적은 파라미터 이름도 `memberId`로 수정해요
- [`Optional<MemberLevel> findByMemberId(long memberId);`](https://github.com/dnd-side-project/dnd-11th-2-backend/compare/fix/%2365/level-up?expand=1#diff-eb5f4d1e3dbec8e1db125cdd66ce4f8c58db70cd2348f56de12d5ba1975f51eaL9)
=> Fix: member level repository의 updateMemberLevel 메서드 반환값을 void로 수정

src/main/java/com/dnd/runus/domain/member/Member.java, src/main/java/com/dnd/runus/infrastructure/persistence/jpa/badge/entity/BadgeEntity.java, src/main/java/com/dnd/runus/infrastructure/persistence/jpa/member/entity/MemberEntity.java, src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordReportResponse.java, src/main/resources/db/migration/V5.0.1__remove_main_badge_alter_badge_image_column.sql, src/test/java/com/dnd/runus/infrastructure/persistence/jpa/member/entity/MemberEntityTest.java
- close #79
- X
- POST `api/v1/running-records`의 반환 필드에서 profileUrl 필드를 삭제합니다.
- member table의 main badge id 컬럼을 삭제합니다.
- badge table의 image_path 컬럼명을 image_url로 변경하고, 타입을 VARCHAR 500으로 변경합니다.
- X
=> Fix: member main badge 컬럼 삭제

src/main/java/com/dnd/runus/application/member/MemberService.java, src/main/java/com/dnd/runus/domain/level/Level.java, src/main/java/com/dnd/runus/domain/member/MemberLevel.java, src/main/java/com/dnd/runus/domain/member/MemberLevelRepository.java, src/main/java/com/dnd/runus/infrastructure/persistence/domain/member/MemberLevelRepositoryImpl.java, src/main/java/com/dnd/runus/infrastructure/persistence/jooq/member/JooqMemberLevelRepository.java, src/main/java/com/dnd/runus/presentation/v1/member/MemberProfileController.java, src/main/java/com/dnd/runus/presentation/v1/member/dto/response/MyProfileResponse.java, src/test/java/com/dnd/runus/application/member/MemberServiceTest.java
- close #75 
- GET `api/v1/members/profiles/me`: 자신의 프로필 조회
- 사용자 자신의 프로필 조회 API를 새롭게 추가합니다.
- 달린 거리를 문자열로 변환하는 로직은 `Level` 도메인 클래스에 두었는데 좋을까요?
- 컨트롤러 테스트는 없고, 서비스 테스트만 추가했어요
=> Feat: member level 현재 경험치 조회 API 추가

src/main/java/com/dnd/runus/domain/level/Level.java, src/test/java/com/dnd/runus/application/member/MemberServiceTest.java, src/test/java/com/dnd/runus/domain/level/LevelTest.java
- #75
- X
- 사용자의 레벨에서 경험치는 지금 기획상에서는 러닝한 meter 단위입니다.
- 경험치를 문자열로 변환할때, 
- X
=> Fix: level formatExp에서 최대 소수점 2자리까지 표현하도록 변경

src/main/java/com/dnd/runus/application/badge/BadgeService.java, src/main/java/com/dnd/runus/domain/badge/BadgeAchievement.java, src/main/java/com/dnd/runus/domain/badge/BadgeAchievementRepository.java, src/main/java/com/dnd/runus/infrastructure/persistence/domain/badge/BadgeAchievementRepositoryImpl.java, src/main/java/com/dnd/runus/infrastructure/persistence/jooq/badge/JooqBadgeAchievementRepository.java, src/main/java/com/dnd/runus/infrastructure/persistence/jooq/badge/JooqBadgeMapper.java, src/main/java/com/dnd/runus/presentation/v1/badge/BadgeController.java, src/main/java/com/dnd/runus/presentation/v1/badge/dto/response/AchievedBadgesResponse.java, src/test/java/com/dnd/runus/application/badge/BadgeServiceTest.java
- close #83 
- GET `api/v1/badges/me`: 사용자가 획득한 배지 정보(이름, 이미지 url, 획득 일자)들을 반환합니다.
- 사용자가 획득한 배지 정보 조회 API를 추가합니다.
- `BadgeAchievement`를 조회할 때, member는 같이 조회할 필요가 없어서, `BadgeAchievement.OnlyBadge`라는 도메인 클래스를 추가했습니다.
- 더 좋은 이름이 있으면 좋을 것 같은데 잘 모르겠어요
- 다른 방법으로는 `badge_achivement` 테이블에서 조회할때 `OnlyBadge`라는 도메인 클래스없이,
`BadgeAchievement` 도메인 클래스를 사용해서 member도 같이 조인해서 조회하는 게 나을까요?
=> Feat: 획득한 badge 조회 API 추가

src/main/java/com/dnd/runus/application/challenge/ChallengeService.java, src/main/java/com/dnd/runus/domain/challenge/ChallengeCondition.java, src/main/java/com/dnd/runus/domain/challenge/GoalType.java, src/main/java/com/dnd/runus/domain/challenge/achievement/dto/ChallengeAchievementDto.java, src/main/java/com/dnd/runus/infrastructure/persistence/jpa/challenge/entity/ChallengeData.java, src/test/java/com/dnd/runus/application/challenge/ChallengeServiceTest.java, src/test/java/com/dnd/runus/domain/challenge/ChallengeTest.java
- 목표 성취 도메인과 같이 사용하기위해 ChallengeGoalType -> GoalType 으로 변경
- 성취 save 메서드 인자 memberId에서 member객체로 변경
- X
- X
- 목표 성취와 같이 사용하면 좋을 것 같아서 ChallengeGoalType을 -> GoalType으로 변경했습니다.
- 챌린지 성취를 저장메서드는 러닝 저장 메서드에서 불러와서 memberId로 find한후 저장한는 것보다 메서드 호출시 member 도메인을 인자로 받는게 좋을 것 같아서 long memberId -> Member member로 변경했습니다.
- 아래 사항 보고 러닝 서비스에 챌린지 관련 로직 추가하시면 될 것 같습니다.
- 러닝 저장 후 -> 러닝 타입이 챌린지 일경우 -> save(Member member, RunningRecord runningRecord, long challengeId) 호출하고 -> ChallengeAchievementDto값을 리턴 값에 추가 하면 될 것 같습니다.
- 러닝 상세 조회 -> 러닝 타입이 챌린지 일경우 findChallengeAchievementBy(long memberId, long runningId) 호출 -> ChallengeAchievementDto값을 리턴 값에 추가 하면 될 것 같습니다.
- findChallengeAchievementBy는 러닝 타입이 없을 을 때 구현 완료 된 값이라, 성취 챌린지가 없을 경우 null 값을 보내 줬는데 추후에 값이 없을 경우 오류 처리를 하는게 좋을 것 같은데 어떻게 생각하시나요?
=> Fix : 챌린지 성취 관련 수정

src/main/java/com/dnd/runus/application/running/RunningRecordService.java, src/main/java/com/dnd/runus/domain/running/RunningRecordRepository.java, src/main/java/com/dnd/runus/infrastructure/persistence/domain/running/RunningRecordRepositoryImpl.java, src/main/java/com/dnd/runus/infrastructure/persistence/jooq/running/JooqRunningRecordRepository.java, src/main/java/com/dnd/runus/presentation/v1/running/RunningRecordController.java, src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordMonthlySummaryResponse.java, src/test/java/com/dnd/runus/application/running/RunningRecordServiceTest.java
- close #106 
- GET `/api/v1/running-records/monthly-summary`
- 홈화면의 이번 달 러닝 기록을 조회하는 기능을 추가합니다.
- 러닝 관련해서 조회하는 기능이라 러닝 컨트롤러와 서비스 쪽에 두었어요.
- 해당 기능을 따로 새로운 도메인쪽(예를 들어 home이라든지)에 분리하는게 좋을까요? 아니면 지금처럼 러닝쪽에 두는게 좋을 까요?
=> Feat: 이번 달 러닝 기록 조회 구현

src/main/java/com/dnd/runus/domain/challenge/achievement/ChallengeAchievement.java, src/main/java/com/dnd/runus/global/constant/RunningResultComment.java, src/main/java/com/dnd/runus/presentation/v1/running/RunningRecordController.java, src/main/java/com/dnd/runus/presentation/v1/running/dto/ChallengeDto.java, src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordAddResultResponse.java
- #87 
- X
- running record 저장시, 반환 response의 필드를 수정합니다.
- 챌린지 결과 문구인 `subTitle`을 포함하도록 합니다.
- `isSuccess` 성공 유무를 추가합니다.
- `expectedTime`을 삭제합니다.
-
=> Fix: running record 저장시 challenge sub title 정보도 반환하도록 변경

src/main/java/com/dnd/runus/infrastructure/persistence/jooq/running/JooqRunningRecordRepository.java, src/test/java/com/dnd/runus/infrastructure/persistence/domain/running/RunningRecordRepositoryImplTest.java
- #106 
- 특정 기간 안에 달린 거리 조회 시 러닝 데이터가 없을 경우 result.value1()이 null인경우에 대해서 오류가 발생합니다.
- result.value1()이 null인경우에 대해 null 인 경우 0을 리턴하게 수정합니다.
- 특정 기간 안에 달린 거리를 조회하는 리파지토리의 테스트 코드를 추가합니다.
-
=> Fix: 이번달 달린 거리 조회시 null 처리 관련 수정

src/main/java/com/dnd/runus/domain/goalAchievement/GoalAchievement.java, src/main/java/com/dnd/runus/presentation/v1/running/dto/GoalResultDto.java, src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordAddResultResponse.java
- #111 
- X
- running record 기록 저장시, `goal` 정보도 반환하도록 수정합니다.
- RunningRecord 서비스에서 achievementMode가 goal일때 저장하는 로직은 추가하지 않았어요!
=> Feat: running record 저장시 목표 성취 정보를 같이 반환하도록 수정

src/main/java/com/dnd/runus/application/weather/WeatherService.java, src/main/java/com/dnd/runus/global/constant/WeatherType.java, src/main/java/com/dnd/runus/presentation/v1/weather/WeatherController.java, src/main/java/com/dnd/runus/presentation/v1/weather/dto/WeatherResponse.java
- close #105 
- GET `api/v1/weathers`: 위도, 경도로 날씨 정보 조회
- 위도, 경도로 날씨 정보를 조회하는 API를 추가합니다.
- 논의한대로, WeatherType enum에 날씨 이름과 문구를 관리하도록 했습니다.
=> Feat: weather 조회 api 추가

src/main/java/com/dnd/runus/infrastructure/persistence/domain/scale/Scale.java, src/main/java/com/dnd/runus/infrastructure/persistence/jpa/scale/entity/ScaleEntity.java, src/main/resources/db/migration/V5.0.8__scale_index.sql
- close #127 
- X
- `scale` 테이블에 달성 단위 순서를 의미하는 `index` 컬럼을 추가합니다.
- postgresql에서 `index`가 컬럼 이름으로 사용될때 문제는 없다고 하는데 `index`라는 이름이 좋을까요?
=> Feat: scale index 순서 컬럼 추가

src/main/java/com/dnd/runus/application/running/RunningRecordService.java
- #90
- X
- `ZoneOffset.of(SERVER_TIMEZONE)` 대신 `defaultZoneOffset`을 사용하도록 합니다.
-
=> Fix: 잘못된 ZoneOffset 대신 defaultZoneOffset을 사용하도록 수정

src/main/java/com/dnd/runus/application/running/RunningRecordService.java
- #132 
- X
- RunningService.getRunningRecordSummaries 메서드에 readOnly 트랜잭션 추가합니다.
- 이를 통해 no session 에러가 없도룩 수정합니다.
-
=> Fix: RunningService.getRunningRecordSummaries 메서드에 readOnly 트랜잭션 추가

src/main/java/com/dnd/runus/application/running/RunningRecordService.java, src/test/java/com/dnd/runus/application/running/RunningRecordServiceTest.java
- close #111
- X
- `RunningRecordService`에 사용자 목표 성취 저장 메서드인 `handleGoalMode()`을 추가합니다.
-
=> Feat: running record 저장시 사용자 목표 성취 저장 함수를 RunningRecordService에 추가

src/main/java/com/dnd/runus/application/scale/ScaleService.java, src/main/java/com/dnd/runus/domain/scale/Scale.java, src/main/java/com/dnd/runus/domain/scale/ScaleRepository.java, src/main/java/com/dnd/runus/domain/scale/ScaleSummary.java, src/main/java/com/dnd/runus/global/constant/ScaleConstant.java, src/main/java/com/dnd/runus/infrastructure/persistence/domain/scale/ScaleRepositoryImpl.java, src/main/java/com/dnd/runus/infrastructure/persistence/jooq/scale/JooqScaleRepository.java, src/main/java/com/dnd/runus/infrastructure/persistence/jpa/scale/entity/ScaleEntity.java, src/main/java/com/dnd/runus/presentation/v1/scale/ScaleController.java, src/main/java/com/dnd/runus/presentation/v1/scale/dto/ScaleSummaryResponse.java, src/test/java/com/dnd/runus/infrastructure/persistence/domain/scale/ScaleRepositoryImplTest.java
- close #135 
- GET `/api/v1/scale/course-summary`
- 지구 한 바퀴 코스 서머리를 조회합니다.
- `Scale` 도메인 클래스를 `com.dnd.runus.infrastructure.persistence.domain.scale` 에서 `com.dnd.runus.domain.scale`로 이동합니다.
-
=> Feat: 지구 한 바퀴 코스 서머리 조회

src/main/java/com/dnd/runus/infrastructure/persistence/jpa/scale/entity/ScaleAchievementEntity.java, src/main/resources/db/migration/V5.0.11__remove_uk_alter_scale_achievement_table.sql
- close #137 
- X
- scale_achievement의 `member_id`, `scale_id`의 유니크키 인덱스를 삭제합니다.
- 지구 한 바퀴 성취 엔티티의 member, scale의 연관 관계를 `@OneToOne` 에서 `@ManyToOne`으로 수정합니다.
-
=> Fix: 지구 한 바퀴 성취 엔티티 member, scale의 연관 관계 수정

src/main/java/com/dnd/runus/application/running/RunningRecordService.java, src/test/java/com/dnd/runus/application/running/RunningRecordServiceTest.java
- #87 
- X
- route에 임시 좌표를 저장하도록 수정합니다.
-
=> Fix: route에 임시 좌표로 running_record를 저장하도록 수정

src/main/java/com/dnd/runus/domain/scale/Scale.java, src/main/java/com/dnd/runus/infrastructure/persistence/jpa/scale/entity/ScaleEntity.java, src/main/resources/db/migration/V5.0.12__add_scale_from_to_column.sql, src/test/java/com/dnd/runus/infrastructure/persistence/domain/scale/ScaleRepositoryImplTest.java
- close #149 
- X
- scale 테이블에 `achievement_value_meter`컬럼(달성 조건 컬럼)을 추가합니다.
- 기존 `size_meter` 컬럼은 시작 지점에서 끝 지점 사이의 거리를 나타내어서 사용자가 해당 코스를 달성했는지 확인하기가 복잡합니다. 따라서 해당 코스를 달성했는지 확인 하기 위해 해당 row의 index이전의 거리의 합을 나타내는 컬럼(달성 조건 거리를 나타내는 컬럼)을 추가합니다.
=> Fix: scale 테이블에 달성 목표 값을 나타내는 achievement_value_meter컬럼 추가

src/main/java/com/dnd/runus/domain/common/Pace.java, src/main/java/com/dnd/runus/presentation/v1/running/dto/RunningRecordMetricsDto.java, src/test/java/com/dnd/runus/domain/common/PaceTest.java
- close #151 
- X
- 기존에는 5'30'' 형태로 역직렬화 했습니다.
- `5'30''`과 `5’30”` 2가지 방식을 허용합니다. (prime 기호인 `’`)
- 직렬화 할때에는 prime 기호를 사용한 `5’30”`을 반환하도록 합니다.
-
=> Fix: Pace json format 형식에서 '가 아닌 prime 기호도 허용하도록 수정

src/main/java/com/dnd/runus/domain/scale/ScaleAchievementLog.java, src/main/java/com/dnd/runus/domain/scale/ScaleAchievementRepository.java, src/main/java/com/dnd/runus/infrastructure/persistence/domain/scale/ScaleAchievementRepositoryImpl.java, src/main/java/com/dnd/runus/infrastructure/persistence/jooq/scale/JooqScaleAchievementRepository.java, src/main/java/com/dnd/runus/infrastructure/persistence/jpa/member/entity/MemberEntity.java, src/main/java/com/dnd/runus/infrastructure/persistence/jpa/running/entity/RunningRecordEntity.java, src/main/java/com/dnd/runus/infrastructure/persistence/jpa/scale/entity/ScaleAchievementEntity.java, src/main/java/com/dnd/runus/infrastructure/persistence/jpa/scale/entity/ScaleEntity.java, src/test/java/com/dnd/runus/infrastructure/persistence/domain/scale/ScaleAchievementRepositoryTest.java, src/test/java/com/dnd/runus/infrastructure/persistence/domain/scale/ScaleRepositoryImplTest.java, src/test/java/com/dnd/runus/infrastructure/persistence/jpa/running/entity/RunningRecordEntityTest.java
- #141 
- X
- scale 기록 조회 함수를 ScaleAchievementRepository에 추가합니다.
- jOOQ를 이용해 구현했고, `ScaleAchievementLog` record 클래스를 추가해 `scale`, `scale_achievement` 테이블의 `achived_date` 만 가져옵니다.
- `scale left join scale_achievement`로 가져오므로 달성일자는 null일수 있습니다. 그래서 `ScaleAchievementLog` 클래스의 `achievedDate` 필드에 `@Nullable`을 달았습니다.
- 추가적으로 엔티티 클래스의 `from()` 함수에서, 도메인 클래스의 id가 0인 경우에 오류가 있었습니다.
- JPA persist 함수 호출시 엔티티 id값이 0이라도 id가 유효하다고 판단해서, 
엔티티 클래스의 `from()` 함수에서 id가 0인 경우에는 엔티티 클래스의 id에 null를 저장하도록 했습니다.
-
=> Feat: scale 기록 조회 함수를 ScaleAchievementRepository에 추가

src/main/java/com/dnd/runus/application/scale/ScaleService.java, src/main/java/com/dnd/runus/presentation/v1/scale/ScaleController.java, src/main/java/com/dnd/runus/presentation/v1/scale/dto/ScaleCoursesResponse.java, src/test/java/com/dnd/runus/application/scale/ScaleServiceTest.java
- close #141 
- GET `api/v1/scale/courses`: 달성 코스 목록 조회
- 달성 코스 목록 조회 API를 추가합니다.
- 코스 정보(개수, 총 거리)
- 달성한 코스들 리스트( 없는 경우, 빈 리스트 )
- 현재 진행중인 코스
- `api/v1/scale/course-summary`에서 반환하던 코스 개수나 거리도 지금 추가하려는 API에 포함시켰어요
=> Feat: scale 코스 목록 조회 API 추가

src/main/java/com/dnd/runus/domain/scale/ScaleRepository.java, src/main/java/com/dnd/runus/infrastructure/persistence/domain/scale/ScaleRepositoryImpl.java, src/main/java/com/dnd/runus/infrastructure/persistence/jooq/scale/JooqScaleRepository.java, src/test/java/com/dnd/runus/infrastructure/persistence/domain/scale/ScaleRepositoryImplTest.java
- #140
- X
- 사용자 member_id, 사용자의 전체 달린 거리에 따라 scale_achievement에 저장할 수 있는 scale_id 리스트를 조회합니다.
- ex)
- 사용자가 이번 러닝에서 2.5km을 뜀
- 사용자의 전체 러닝 달린 기록이 3km
- `scale` 기준이 아래와 같음
-  id:1, 코스1, 누적 거리 500m, 순서:1
-  id:2, 코스2, 누적 거리 1km, 순서:2
-  id:3, 코스3, 누적 거리 3km, 순서 3
- 현재 `scale_achievement` 테이블에 저장 된 사용자의 데이터 값
- scale_id가 1인 데이터
- 위의 예시의 경우 이번 러닝에서 `scale_achievement`에 저장할 수 있는 `scale_id` 값은 2, 3이 되고 `findAchievableScaleIds`은 [2,3]을 반환하다.
-
=> Feat: 저장할 수 있는 scale_id 리스트 조회 repository

src/main/java/com/dnd/runus/domain/scale/Scale.java, src/main/java/com/dnd/runus/domain/scale/ScaleAchievement.java, src/main/java/com/dnd/runus/domain/scale/ScaleAchievementRepository.java, src/main/java/com/dnd/runus/infrastructure/persistence/domain/scale/ScaleAchievementRepositoryImpl.java, src/main/java/com/dnd/runus/infrastructure/persistence/jpa/scale/JpaScaleAchievementRepository.java, src/main/java/com/dnd/runus/infrastructure/persistence/jpa/scale/entity/ScaleAchievementEntity.java, src/test/java/com/dnd/runus/infrastructure/persistence/domain/scale/ScaleAchievementRepositoryTest.java
- #140 
- X
- `scale_achievement`의 데이터를 저장하는 함수를 리파지토리에 추가합니다.
- `ScaleAchievement` 도메인의 `id`를 사용하지 않아 삭제합니다.
- `id`로 `Scale` 도메인을 생성할 수 있는 생성자를 추가합니다.
- 사용자가 저장할 수 있는 scale_id 값을 조회 -> 알맞게 `ScaleAchievement`로 변환 후 저장할 예정입니다.
-
=> Feat: ScaleAchievement 저장 함수 리파지토리 추가

src/main/java/com/dnd/runus/application/running/RunningRecordService.java, src/main/java/com/dnd/runus/domain/challenge/ChallengeWithCondition.java, src/main/java/com/dnd/runus/infrastructure/persistence/jpa/challenge/entity/ChallengeAchievementEntity.java
- close #159 
- X
- challenge_achievement_percentage저장 시 challenge_achievement_id null 관련 버그를 수정합니다.
- 저장된 `ChallengeAchievement`의 id값이 필요 하므로, 챌린지 펀센티이지 저장 시 `new ChallengeAchievementRecord(achievement, achievementRecord.percentageValues())` 로 새로운 ChallengeAchievementRecord객체를 생성합니다.
- `ChallengeAchievementEntity`의 from 메서드에 id값을 셋팅하는 코드를 추가합니다.
- 데이터 잘못 저장되는 버그(퍼센테이지 저장 유무가 false인 조건이 하나라도 있는 경우, 퍼센테이지가 저장됨.)를 수정합니다.
-
=> Fix: 챌린지 성취 퍼센테이지 저장 버그 수정

src/main/java/com/dnd/runus/application/running/RunningRecordService.java, src/main/java/com/dnd/runus/infrastructure/persistence/jooq/scale/JooqScaleRepository.java, src/test/java/com/dnd/runus/application/running/RunningRecordServiceTest.java, src/test/java/com/dnd/runus/infrastructure/persistence/domain/scale/ScaleAchievementRepositoryTest.java, src/test/java/com/dnd/runus/infrastructure/persistence/domain/scale/ScaleRepositoryImplTest.java
- close #140 
- X
- 러닝 이 저장 되면 아래의 순서로 사용자의 지구 한 바퀴 성취 기록이 저장 됩니다.
- 사용자의 전체 달린 거리, 기존의 사용자의 지구 한 바퀴 성취 기록을 이용해 사용자가 성취 할 수 있는 지구 한 바퀴 id를 조회하는 `scaleRepository.findAchievableScaleIds(member.memberId())`를 호출 합니다.
- 사용자가 성취 할 수 있는 지구 한 바퀴 id가 존재 하면, 사용자의 지구 한 바퀴 성취 기록을 저장합니다.
-
=> Feat: 러닝 저장 시 사용자 ScaleAchievement 저장 로직 추가 

src/main/java/com/dnd/runus/domain/challenge/achievement/ChallengeAchievementPercentageRepository.java, src/main/java/com/dnd/runus/infrastructure/persistence/domain/challenge/ChallengeAchievementPercentageRepositoryImpl.java, src/main/java/com/dnd/runus/infrastructure/persistence/jpa/challenge/JpaChallengeAchievementPercentageRepository.java, src/test/java/com/dnd/runus/infrastructure/persistence/domain/challenge/ChallengeAchievementPercentageRepositoryImplTest.java
- #162 
- X
- 회원 탈퇴를 위해 ChallengeAchievementPercentageRepository에 삭제 메서드를 추가합니다.
-
=> Feat: 회원 탈퇴를 위한 챌린지 성취 퍼센테이지 삭제 메서드 구현

src/main/java/com/dnd/runus/domain/goalAchievement/GoalAchievementRepository.java, src/main/java/com/dnd/runus/infrastructure/persistence/domain/goalAchievement/GoalAchievementRepositoryImpl.java, src/main/java/com/dnd/runus/infrastructure/persistence/jpa/goalAchievement/JpaGoalAchievementRepository.java, src/test/java/com/dnd/runus/infrastructure/persistence/domain/goalAchievement/GoalAchievementRepositoryImplTest.java
- #162 
- 
- 회원 탈퇴를 위해 GoalAchievementRepository에 삭제 메서드를 추가합니다.
-
=> Feat: 회원 탈퇴를 위한 GoalAchievementRepository 삭제 메서드 구현

src/main/java/com/dnd/runus/domain/running/RunningRecordRepository.java, src/main/java/com/dnd/runus/infrastructure/persistence/domain/running/RunningRecordRepositoryImpl.java, src/main/java/com/dnd/runus/infrastructure/persistence/jpa/running/JpaRunningRecordRepository.java, src/test/java/com/dnd/runus/infrastructure/persistence/domain/running/RunningRecordRepositoryImplTest.java
- #162 
- X
- 회원 탈퇴를 위해 멤버 아이디로 모든 러닝 기록을 찾는 메서드를 RunningRecordRepository에 추가합니다.
-
=> Feat: 회원 탈퇴를 위한 멤버 아이디로 러닝 데이터 찾는 메서드 구현

src/main/java/com/dnd/runus/domain/scale/ScaleAchievementRepository.java, src/main/java/com/dnd/runus/infrastructure/persistence/domain/scale/ScaleAchievementRepositoryImpl.java, src/main/java/com/dnd/runus/infrastructure/persistence/jpa/scale/JpaScaleAchievementRepository.java, src/test/java/com/dnd/runus/infrastructure/persistence/domain/scale/ScaleAchievementRepositoryImplTest.java
- #162 
- X
- 회원 탈퇴를 위해 ScaleAchievementRepository에 삭제 메서드를 추가합니다.
-
=> Feat: 회원 탈퇴를 위한 ScaleAchievementRepository에 삭제 메서드 구현

src/main/java/com/dnd/runus/domain/challenge/achievement/ChallengeAchievementRepository.java, src/main/java/com/dnd/runus/infrastructure/persistence/domain/challenge/ChallengeAchievementRepositoryImpl.java, src/main/java/com/dnd/runus/infrastructure/persistence/jpa/challenge/JpaChallengeAchievementRepository.java, src/test/java/com/dnd/runus/infrastructure/persistence/domain/challenge/ChallengeAchievementRepositoryImplTest.java
- #162 
- X
- 회원 탈퇴를 위해 ChallengeAchievementRepository에 관련 메서드를 추가합니다.
- `List<RunningRecord>`로 ChallengeAchievement의 id 리스트를 찾는 메서드를 추가합니다.
- ChallengeAchievement의 id로 챌린지 성취 값을 삭제하는 메서드를 추가합니다.
-
=> Feat: 회원 탈퇴를 위한 ChallengeAchievementRepository에 관련 메서드 구현

src/main/java/com/dnd/runus/presentation/v1/scale/dto/ScaleCoursesResponse.java, src/test/java/com/dnd/runus/application/scale/ScaleServiceTest.java
- close #172 
- X
- `api/v1/scale/courses` API에서 달성 기록 목록 조회 시 반환하는 meter 단위 int 타입을 string으로 변경합니다.
-
=> Fix: int 타입의 meter 대신 string 타입으로 반환하도록 달성 코스 기록 API 수정

src/main/java/com/dnd/runus/application/member/MemberService.java, src/main/java/com/dnd/runus/presentation/v1/member/dto/response/MyProfileResponse.java, src/test/java/com/dnd/runus/application/member/MemberServiceTest.java
- close #174 
- X
- `api/v1/profiles/me` API의 반환값에 현재 레벨 이름 필드를 추가하여 반환합니다.
-
=> Fix: 프로필 조회 API의 반환값에 현재 레벨 이름 필드를 추가

src/main/java/com/dnd/runus/domain/goalAchievement/GoalAchievement.java, src/main/java/com/dnd/runus/domain/level/Level.java, src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordMonthlySummaryResponse.java
- x
- x
- 코드 로직 변경없이 km 단위 문자열로 변환하는 로직을 DecimalFormat을 사용하도록 수정
- `GoalAchievement`에서 문자열로 변환시 대문자인 `KM`를 사용했는데 소문자인 `km`로 변경합니다. 
- `RunningRecordMonthlySummaryResponse`의 스웨거 문서 오타를 수정합니다.
- `Leve 2` -> `Level 2`
-
=> Refactor: km 단위 문자열로 변환하는 로직을 DecimalFormat을 사용하도록 수정

src/main/java/com/dnd/runus/application/oauth/OauthService.java, src/main/java/com/dnd/runus/auth/oidc/provider/OidcProvider.java, src/main/java/com/dnd/runus/presentation/v1/oauth/OauthController.java, src/test/java/com/dnd/runus/application/oauth/OauthServiceTest.java, src/test/java/com/dnd/runus/infrastructure/persistence/domain/challenge/ChallengeAchievementPercentageRepositoryImplTest.java, src/test/java/com/dnd/runus/infrastructure/persistence/domain/challenge/ChallengeAchievementRepositoryImplTest.java, src/test/java/com/dnd/runus/infrastructure/persistence/domain/scale/ScaleAchievementRepositoryImplTest.java
- close #162 
- POST `/api/v1/auth/oauth/withdraw`
- 기존에 하나의 트랜젝션으로 존재했던 소셜 회원 연결 해제(네트워크 연결) + 회원 데이터 삭제 로직을 분리합니다.
- 소셜 회원 연결 해제는 revokeOauth 메서드를 호출해 회원이 로그인한 3rd party 연동을 해제합니다.
-  소셜 회원 연결 해제가 완료 되었으면 회원의 데이터를 삭제(hard delete)을 위해 deleteAllDataAboutMember메서드를 호출합니다.
- https://github.com/dnd-side-project/dnd-11th-2-backend/pull/167#discussion_r1751633667 에서 PR 수정 사항을 [10ac56c](https://github.com/dnd-side-project/dnd-11th-2-backend/pull/179/commits/10ac56c68568ef4b2bec4883cda549fd28060811)에서 수정했습니다.
=> Refactor: 회원탈퇴 로직 리팩터링(hard delete)

src/main/java/com/dnd/runus/domain/goalAchievement/GoalAchievement.java, src/main/java/com/dnd/runus/presentation/v1/running/dto/GoalResultDto.java, src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordAddResultResponse.java
- close #185 
- X
- running record 저장 시 목표한 goal에 맞는 성공과 미달 이미지를 반환하도록 합니다.
- S3 버킷에 성공, 미달 이미지 2개를 추가했어요
-
=> Feat: running record 저장 시 goal 성공과 미달 이미지 추가

src/main/java/com/dnd/runus/application/running/RunningRecordService.java, src/main/java/com/dnd/runus/global/exception/BusinessException.java, src/main/java/com/dnd/runus/global/exception/type/ErrorType.java, src/main/java/com/dnd/runus/presentation/v1/running/RunningRecordController.java, src/main/java/com/dnd/runus/presentation/v1/running/dto/request/RunningRecordRequest.java, src/test/java/com/dnd/runus/application/running/RunningRecordServiceTest.java
- close #177 
- X
- `RunningRecordRequest` 클래스에 잘못된 로직의 경우 예외를 던지도록 합니다.
- `startAt`이 `endAt`보다 늦은 경우 `START_AFTER_END` 예외를 던집니다.
- `achievementMode`가 `CHALLENGE`이고 `goalDistance`나 `goalTime`이 존재하는 경우 `CHALLENGE_MODE_WITH_PERSONAL_GOAL` 예외
- `achievementMode`가 `GOAL`이고 `challengeId`가 존재하는 경우 `GOAL_MODE_WITH_CHALLENGE_ID` 예외
- `achievementMode`가 `GOAL`이고 `goalDistance`와 `goalTime`이 모두 존재하는 경우 `GOAL_TIME_AND_DISTANCE_BOTH_EXIST` 예외
- startAt, endAt 검증 로직이 request dto 클래스로 옮기므로, 시작 시간이 더 느린지 검증하는 `RunningRecordService` 테스트 케이스는 삭제합니다.
-
=> Fix: RunningRecordRequest 클래스에 validation 추가

src/main/java/com/dnd/runus/domain/running/RunningRecordRepository.java, src/main/java/com/dnd/runus/infrastructure/persistence/domain/running/RunningRecordRepositoryImpl.java, src/main/java/com/dnd/runus/infrastructure/persistence/jooq/running/JooqRunningRecordRepository.java, src/test/java/com/dnd/runus/infrastructure/persistence/domain/running/RunningRecordRepositoryImplTest.java
- #180 
- X
- 활동요약 API을 위해, 기간 안에 일별로 달린 시간을 조회하는 함수를 러닝 리파지토리에 추가합니다.
-
=> Feat: 일별 달린 시간을 조회하는 함수 리파지토리에 추가

src/main/java/com/dnd/runus/infrastructure/persistence/jooq/JooqConfig.java, src/main/java/com/dnd/runus/infrastructure/persistence/jpa/JpaConfig.java, src/main/java/com/dnd/runus/presentation/config/SwaggerConfig.java, src/test/java/com/dnd/runus/infrastructure/persistence/annotation/RepositoryTest.java
- x
- x
- 파일 위치가 불분명한 `global.config` 패키지 대신 역할에 맞는 패키지로 config 파일들을 옮깁니다.
- JooqConfig: `infrastructure.persistence.jooq`
- JpaConfig: `infrastructure.persistence.jpa`
- SwaggerConfig: `presentation.config`
-
=> Rename: config 파일들을 global config 패키지 대신 jooq, jpa, swagger 패키지 사용

src/main/java/com/dnd/runus/application/oauth/OauthService.java, src/test/java/com/dnd/runus/application/oauth/OauthServiceTest.java
- x
- x
- `OauthService`의 `signIn`, `signUp` 메서드에서 `SocialProfile` 조회 후 `member`를 다시 조회하고 있어요
- `SocialProfile`이 `Member`를 필드로 가지고 있으므로 member id로 조회하는 대신 SocialProfile.Member 필드를 사용하도록 수정합니다.
- `OauthService`의 `signIn`, `signUp` 메서드 성공, 예외 발생 케이스를 추가합니다.
- sign-in 시 socialProfile이 있다면 성공
- sign-in 시 socialProfile이 없다면 에러 타입이 USER_NOT_FOUND인 BusinessException 에러 발생
- sign-up 시 socialProfile이 있다면 해당 socialProfile을 사용
- sign-up 시 socialProfile이 없다면 socialProfileRepository.save() 호출
-
=> Test: OauthService sign in, up 메서드 테스트 추가

src/main/java/com/dnd/runus/auth/oidc/provider/JwtParser.java, src/main/java/com/dnd/runus/auth/oidc/vo/OidcPublicKeys.java, src/main/java/com/dnd/runus/global/exception/type/ErrorType.java
- close #195 
- X
- oidc jwt token parser에서 `FAILED_PARSING` 대신 `INVALID_BASE64` 에러 타입을 사용합니다.
- kid, alg이 일치하는 경우가 없는 경우, 에러 메세지에 이 내용을 포함하도록 수정합니다.
-
=> Fix: apple token 파싱 로직 base64, kid, alg 불일치 로그 메세지 구체화

src/main/java/com/dnd/runus/application/running/RunningRecordService.java, src/main/java/com/dnd/runus/global/constant/MetricsConversionFactor.java, src/main/java/com/dnd/runus/presentation/handler/ExceptionRestHandler.java, src/main/java/com/dnd/runus/presentation/v1/running/RunningRecordController.java, src/main/java/com/dnd/runus/presentation/v1/running/dto/request/RunningRecordWeeklySummaryType.java, src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordWeeklySummaryResponse.java, src/test/java/com/dnd/runus/application/running/RunningRecordServiceTest.java
- close #180 
- GET `/api/v1/running-records/weekly-summary`
- 활동 요약 조회 API을 추가합니다.
- 활동 요약을 조회하는 서비스 단 함수를 추가합니다.
- `@RequestParam`으로 받을 경우, 
타입에 대한 불일치에 관한 예외 처리와
요청 파라미터 타입이 Enum일 때 Validation에 관한 예외 처리를 위해 `MethodArgumentTypeMismatchException.class`에 관한 ExceptionHandler을 추가합니다.
- 해당 기능의 화면이 아직 명확하지 않아 `RunningRecordWeeklySummaryResponse`는 바뀔 가능 성이 있습니다.
- 현재는 클라이언트분과 상의 하에 임시로 구성해두었습니다.
=> Feat: 활동 요약 조회 API

src/main/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherHttpClient.java, src/test/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherHttpClientTest.java
- x
- x
- unit에서 units로 오타를 수정합니다.
- #129 에서 해결된 줄 알았으나 `units`이 아닌 `unit`으로 잘못 작성했습니다.
- java 코드 상에서 사용하는 param 이름을 현재 프로젝트에서 사용중인 것과 동일한 이름으로 통일합니다.
- lon -> longitude
- lat -> latitude
-
=> Fix: openweathermap api 요청 시 unit을 units로 오타 수정

src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordSummaryResponse.java, src/main/java/com/dnd/runus/presentation/v1/scale/dto/ScaleCoursesResponse.java
- X
- X
- 인너 클래스 네임이 같은 문제로 스웨거에 RunningRecordSummaryResponse의 Info가 ScaleCoursesResponse Info로 표시되는 문제 해결합니다.
- RunningRecordSummaryResponse의 Info와 ScaleCoursesResponse의 Info에 각각 스키마 네임을 지정합니다.
-
=> Fix: daily 러닝 기록 조회 api 문서 오류 수정

src/main/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherClient.java, src/main/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherInfo.java, src/test/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherHttpClientTest.java
- close #204
- x
- openweathermap api 요청 시 반환 dto 필드를 camel case로 수정합니다.
- feels_like -> feelsLike
- temp_min -> tempMin
- temp_max -> tempMax
-
=> Fix: openweathermap api 요청 시 반환 dto 필드를 camel case로 수정

src/main/java/com/dnd/runus/global/exception/type/ErrorType.java, src/main/java/com/dnd/runus/presentation/v1/weather/WeatherController.java
- close #205 
- x
- GET `api/v1/weathers` API에서 에러가 발생하는 경우, 500 에러에서 503 에러로 변경합니다.
- 해당 API docs `ApiErrorType`에 `ErrorType.WEATHER_API_ERROR`를 추가합니다.
-
=> Fix: WEATHER_API_ERROR의 http status code를 500에서 503으로 수정

build.gradle.kts, gradle/libs.versions.toml, src/main/java/com/dnd/runus/infrastructure/weather/WeatherClientProxy.java, src/main/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherHttpClientConfig.java, src/main/java/com/dnd/runus/infrastructure/weather/weatherapicom/WeatherApiComWeatherClient.java, src/main/java/com/dnd/runus/infrastructure/weather/weatherapicom/WeatherapicomWeatherHttpClientConfig.java, src/main/java/com/dnd/runus/presentation/v1/weather/WeatherController.java, src/main/resources/application.yml
- close #212 
- x
- `resilience4j` 의존성을 추가합니다.
- `openweathermap` api를 메인으로 사용하고, 해당 API를 사용할 수 없는 경우 `weatherApiCom` api를 사용합니다.
- resilience4j의 circuit breaker 상태 정보를 actuator에서 확인할 수 있도록 application.yml에 설정합니다.
- 위에서 언급한 날씨 api 2개 모두 timeout 시간을 변경합니다.
- read timeout: 5초 -> 1초
- connection timeout: 10초 -> 3초
- main, fallback api 모두 실패한 경우, 에러 로그를 남기고 빈 날씨 응답값을 반환하도록 합니다.
-
=> Feat: circuit breaker로 날씨 API 이중화

src/main/java/com/dnd/runus/global/constant/CacheType.java, src/main/java/com/dnd/runus/infrastructure/weather/WeatherClientProxy.java
- close #214 
- x
- 외부 weather api 캐싱 어노테이션을 `WeatherClientProxy`.`getWeatherInfo` 메서드에 추가합니다.
- 캐싱 key는 `경도:위도`를 사용합니다.
- 캐싱 유지 기간은 날씨 api 특성 상, 오래 유지할 필요가 없으므로 10분으로 설정합니다.
-
=> Feat: 외부 weather api 캐싱 어노테이션을 WeatherClientProxy.getWeatherInfo 메서드에 추가

src/main/java/com/dnd/runus/application/server/DeviceType.java, src/main/java/com/dnd/runus/application/server/ServerVersionService.java, src/main/java/com/dnd/runus/application/server/Version.java, src/main/java/com/dnd/runus/presentation/v1/server/ServerController.java, src/test/java/com/dnd/runus/application/server/VersionTest.java
- close #142
- x
- 백엔드 서버 코드에 `DeviceType`이라는 enum으로 앱 최소 요구 버전을 작성합니다. 
- 앱 버전 업데이트나 신규 기능으로 구버전 앱을 지원하지 않는 경우 해당 enum 값을 수정합니다.
-
=> Feat: DeviceType, Version, ServerVersionService 클래스 추가

src/main/java/com/dnd/runus/domain/common/Pace.java, src/test/java/com/dnd/runus/domain/common/PaceTest.java
- x
- x
- Pace. getPace 메서드에서 기존에는 초 단위가 10 미만이면 한 자리로 표현합니다. (`5’5”`)
- 초 단위가 10 미만이더라도 두 자리로 표현하도록 수정합니다. (`5’05”`)
- 검증하는 테스트를 추가합니다.
- 분 또는 초는 0 이상 60 미만의 값이 아닌 경우에 생성자에서 IllegalArgumentException 예외를 던지도록 추가합니다.
-
=> Fix: Pace getJsonValue 메서드에서 초를 두 자리로 표현

src/main/java/com/dnd/runus/application/oauth/OauthService.java, src/main/java/com/dnd/runus/auth/oidc/client/RestClientConfig.java, src/main/java/com/dnd/runus/auth/oidc/provider/apple/AppleOidcProvider.java, src/main/java/com/dnd/runus/global/exception/type/ErrorType.java, src/main/resources/application.yml, src/test/java/com/dnd/runus/application/oauth/OauthServiceTest.java, src/test/resources/application.yml
- #56 
- x
- 기존에는 oidcProvider에서 access token과 revoke api 호출을 기다리고 `revokeOauth` 메서드를 종료합니다.
- access token을 얻는 api와 revoke api 호출을 비동기로 변경합니다.
- 이렇게 함으로 트랜잭션은 바로 종료되고 revoke api 호출은 다른 가상 스레드에서 실행됩니다.
- revoke api가 실패한 경우 로그를 남기도록 했습니다.
-
=> Refactor: OauthService.revokeOauth 메서드에서 revoke 호출을 가상 스레드를 이용한 비동기 호출로 변경

src/main/java/com/dnd/runus/application/running/RunningRecordService.java, src/main/java/com/dnd/runus/presentation/v1/running/RunningRecordController.java, src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordQueryResponse.java, src/test/java/com/dnd/runus/application/running/RunningRecordServiceTest.java
- close #225 
- GET api/v1/running-records/{runningRecordId} - 러닝 기록 id로 러닝 상세 기록 조회 api
- 위 api를 새롭게 추가합니다.
- 관련 service test를 추가합니다.
- 해당 member가 아닌 다른 member의 러닝 기록을 조회하는 경우 NotFound 예외를 발생하도록 했습니다.
-
=> Feat: running record id로 러닝 기록 조회 api 추가

src/main/java/com/dnd/runus/presentation/handler/ExceptionRestHandler.java, src/main/java/com/dnd/runus/presentation/v1/running/RunningRecordController.java
- x
- x
- 기존에 `{runningRecordId}`에서 `/{runningRecordId}`으로 수정합니다.
- uri 경로에 `/`가 빠져 Get 요청으로 인식하지 못하는 버그를 수정합니다.
- `InsufficientAuthenticationException` 예외 처리를 `ExceptionRestHandler`에 추가합니다.
-
=> Fix: running record 조회 api에서 잘못된 uri 매핑 수정

src/main/java/com/dnd/runus/application/config/TransactionEventHandler.java, src/main/java/com/dnd/runus/global/event/AfterTransactionEvent.java, src/main/java/com/dnd/runus/global/event/BeforeTransactionEvent.java, src/main/java/com/dnd/runus/global/event/TransactionEvent.java
- close #230 
- x
- `TransactionEventHandler` 클래스를 추가합니다.
- `BeforeTransactionEvent`, `AfterTransactionEvent` 이벤트를 받아 별도의 트랜잭션에서 처리합니다.
- 비동기 처리에 사용할 스레드는 별도의 PR에서 진행될 예정입니다.
- #229
-
=> Feat: TransactionEventHandler 클래스 추가

src/main/java/com/dnd/runus/infrastructure/weather/weatherapicom/WeatherApiComWeatherClient.java, src/main/java/com/dnd/runus/infrastructure/weather/weatherapicom/dto/WeatherapicomCurrent.java, src/main/java/com/dnd/runus/infrastructure/weather/weatherapicom/dto/WeatherapicomHistory.java, src/test/java/com/dnd/runus/infrastructure/weather/weatherapicom/WeatherApiComWeatherClientTest.java
- close #237 
- x
- 기존에는 `현재 기온` API, `일일 최고/최저 기온` API를 순차적으로 요청합니다.
- 2개의 API를 비동기로 호출한 다음, 2개의 응답들을 기다리도록 변경합니다.
- 기존에는 `getWeatherInfo()` 메서드에서 weatherapicom API dto값에 null이 있는지 검증합니다.
- 응답 dto 생성자에서 응답값에 null이 있는지 검증하도록 합니다.
-
=> Refactor: WeatherApiComWeatherClient.getWeatherInfo 메서드 내 API 2개 동기 호출을 비동기로 전환

src/main/resources/application.yml, src/test/resources/application.yml
- #198 
- x
- 기본 hibernate 로그는 다음과 같습니다. (색상 x)
```sql
Hibernate: select me1_0.id,me1_0.created_at,me1_0.nickname,me1_0.role,me1_0.updated_at from member me1_0 where me1_0.id=?
```
- SQL 쿼리를 포매팅하여 Logback을 사용해 로그로 출력하고, 세션 정보도 출력하도록 합니다.
```jsonc
Session Metrics {
0 nanoseconds spent acquiring 0 JDBC connections;
0 nanoseconds spent releasing 0 JDBC connections;
0 nanoseconds spent preparing 0 JDBC statements;
0 nanoseconds spent executing 0 JDBC statements;
0 nanoseconds spent executing 0 JDBC batches;
0 nanoseconds spent performing 0 L2C puts;
0 nanoseconds spent performing 0 L2C hits;
0 nanoseconds spent performing 0 L2C misses;
0 nanoseconds spent executing 0 flushes (flushing a total of 0 entities and 0 collections);
0 nanoseconds spent executing 0 pre-partial-flushes;
0 nanoseconds …
```
=> Feat: Hibernate 로그 레벨 설정

src/main/java/com/dnd/runus/application/member/MemberWithdrawService.java, src/main/java/com/dnd/runus/application/oauth/OauthService.java, src/main/java/com/dnd/runus/presentation/v1/oauth/OauthController.java, src/test/java/com/dnd/runus/application/member/MemberWithdrawServiceTest.java, src/test/java/com/dnd/runus/application/oauth/OauthServiceTest.java
- close #56 
- x
- `OauthService.deleteAllDataAboutMember()` 메서드를 `MemberWithdrawService` 클래스로 분리합니다.
- 기존에는 OauthController에서 revokeOauth() 메서드와 `deleteAllDataAboutMember()` 메서드를 호출합니다.
- 트랜잭션을 분리하기 위함인데, 이를 spring event를 발생하도록 수정합니다.
- 테스트 코드 내부 변경 없이 테스트 파일만 분리합니다.
-
=> Refactor: OauthService.deleteAllDataAboutMember 메서드를 MemberWithdrawService 클래스로 분리

src/main/java/com/dnd/runus/application/running/RunningRecordService.java, src/main/java/com/dnd/runus/domain/challenge/achievement/ChallengeAchievement.java, src/main/java/com/dnd/runus/domain/challenge/achievement/ChallengeAchievementRepository.java, src/main/java/com/dnd/runus/infrastructure/persistence/domain/challenge/ChallengeAchievementRepositoryImpl.java, src/main/java/com/dnd/runus/infrastructure/persistence/jooq/challenge/JooqChallengeAchievementRepository.java, src/main/java/com/dnd/runus/infrastructure/persistence/jpa/challenge/entity/ChallengeEntity.java, src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordQueryResponse.java, src/test/java/com/dnd/runus/application/running/RunningRecordServiceTest.java, src/test/java/com/dnd/runus/infrastructure/persistence/domain/challenge/ChallengeAchievementRepositoryImplTest.java
- close #225 
- x
- id로 running record 조회 시 challenge나 goal 성취도 같이 조회하도록 수정합니다.
- running_record, challenge, challenge_achievement, goal_achievement 테이블들을 Left Join으로 묶어 데이터를 가져오려고 했으나, challenge_achivement와 goal_achivement은 양립할 수 없는 옵셔널 관계에요
- challenge가 있을 때 goal이 없고, goal이 있을 때는 challenge가 없는 구조
- 새로운 메서드를 추가하기 애매해서 기존 코드와 로직을 활용하여 필요한 데이터를 일관되게 가져오는 방식으로 구현했어요
1. running_record 찾기
2. challenge_achivement + challenge
a. 챌린지 정보가 있다면 바로 반환
b. 챌린지 정보가 없다면 goal_achivement를 찾기
left join 대신 이 방식이 적절할까요?
=> Fix: running record 조회 시 challenge나 goal 성취도 같이 조회하도록 수정

src/main/java/com/dnd/runus/application/running/RunningRecordService.java, src/main/java/com/dnd/runus/domain/running/RunningRecord.java, src/main/java/com/dnd/runus/infrastructure/persistence/jooq/running/JooqRunningRecordRepository.java, src/main/java/com/dnd/runus/infrastructure/persistence/jpa/running/entity/RunningRecordEntity.java, src/main/resources/db/migration/V5.0.12__running_record_add_timezone_name.sql, src/test/java/com/dnd/runus/application/member/MemberWithdrawServiceTest.java, src/test/java/com/dnd/runus/application/running/RunningRecordServiceTest.java, src/test/java/com/dnd/runus/infrastructure/persistence/domain/challenge/ChallengeAchievementPercentageRepositoryImplTest.java, src/test/java/com/dnd/runus/infrastructure/persistence/domain/challenge/ChallengeAchievementRepositoryImplTest.java, src/test/java/com/dnd/runus/infrastructure/persistence/domain/goalAchievement/GoalAchievementRepositoryImplTest.java, src/test/java/com/dnd/runus/infrastructure/persistence/domain/running/RunningRecordRepositoryImplTest.java, src/test/java/com/dnd/runus/infrastructure/persistence/domain/scale/ScaleRepositoryImplTest.java, src/test/java/com/dnd/runus/infrastructure/persistence/jpa/running/entity/RunningRecordEntityTest.java
- close #242
- x
- RunningRecord startAt과 endAt 필드를 `OffsetDateTime`에서 `ZonedDateTime`으로 변경합니다.
- running_record 테이블에 timezone을 의미하는 `timezone_name` VARCHAR 컬럼을 추가합니다.
- `+09:00`이나 `Asia/Seoul`을 저장해 timezone 정보에 맞게 시간을 ZonedDateTime 객체로 불러옵니다.
-
=> Feat: RunningRecord startAt과 endAt 필드를 OffsetDateTime에서 ZonedDateTime으로 변경

src/main/java/com/dnd/runus/domain/badge/Badge.java, src/main/java/com/dnd/runus/domain/badge/BadgeRepository.java, src/main/java/com/dnd/runus/domain/badge/BadgeWithAchieveStatusAndAchievedAt.java, src/main/java/com/dnd/runus/global/constant/BadgeType.java, src/main/java/com/dnd/runus/infrastructure/persistence/domain/badge/BadgeRepositoryImpl.java, src/main/java/com/dnd/runus/infrastructure/persistence/jooq/badge/JooqBadgeRepository.java, src/main/java/com/dnd/runus/infrastructure/persistence/jpa/badge/entity/BadgeEntity.java, src/test/java/com/dnd/runus/application/badge/BadgeServiceTest.java, src/test/java/com/dnd/runus/infrastructure/persistence/domain/badge/BadgeRepositoryTest.java
- #236 
- X
- 나의 뱃지 목록 조회 API를 위한 리파지토리를 구현합니다.
- 사용자의 뱃지 성취 여부, 뱃지의 카테고리 분류(배지 타입, 최신 획득한 배지)를 위해 left join을 사용해서 조회합니다.
- `BadgeType`의 `RUNNING_COUNT` 값을 연속이라는 의미를 명확하게 하기 위해 `STREAK`로 변경합니다.
-
=> Feat: 나의 뱃지 목록 조회 리파지토리 구현

src/main/java/com/dnd/runus/global/constant/WeatherType.java, src/main/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherClient.java, src/main/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherInfo.java, src/main/java/com/dnd/runus/infrastructure/weather/weatherapicom/WeatherApiComWeatherClient.java, src/main/java/com/dnd/runus/infrastructure/weather/weatherapicom/dto/WeatherapicomCurrent.java, src/test/java/com/dnd/runus/infrastructure/weather/openweathermap/OpenweathermapWeatherHttpClientTest.java
- close #251 
- x
- 밤 버전 날씨 아이콘을 추가합니다.
- `CLEAR_NIGHT`, `CLOUDY_NIGHT`
- `WeatherClient` 구현 클래스들에서 `CLEAR`, `CLOUDY`인 경우 밤 버전도 반환하도록 합니다.
- `WeatherType` 이미지 url을 type 이름을 넣도록 수정합니다.
-
=> Feat: 밤 버전 날씨 아이콘 추가

src/main/java/com/dnd/runus/domain/common/Pace.java, src/test/java/com/dnd/runus/domain/common/PaceTest.java
- close #255
- x
- Pace 객체를 파싱이나 직렬화할 때, `0’00”` 대신 `-’--”`을 사용하도록 수정합니다.
-
=> Fix: 0초인 Pace를 파싱이나 직렬화 할 때 0 대신 -를 사용하도록 수정

src/main/java/com/dnd/runus/application/running/RunningRecordService.java, src/main/java/com/dnd/runus/domain/common/Pace.java, src/main/java/com/dnd/runus/presentation/v1/running/dto/RunningRecordMetricsDtoForAdd.java, src/main/java/com/dnd/runus/presentation/v1/running/dto/RunningRecordMetricsForAddDto.java, src/main/java/com/dnd/runus/presentation/v1/running/dto/request/RunningRecordRequest.java, src/test/java/com/dnd/runus/application/running/RunningRecordServiceTest.java
- close #257 
- X
- 평균페이스가 없는 `RunningRecordMetricsDtoForAdd.java` dto를 새로 추가 합니다. 
- 달린 거리와 시간으로 평균페이스를 계산하는 `calAvgPace` 함수를 추가합니다.
-
=> Fix: 평균페이스를 서버에서 계산하도록 수정

src/main/java/com/dnd/runus/application/running/RunningRecordService.java, src/main/java/com/dnd/runus/presentation/v1/running/RunningRecordController.java, src/main/java/com/dnd/runus/presentation/v1/running/dto/WeeklyRunningRatingDto.java, src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordWeeklySummaryResponse.java, src/test/java/com/dnd/runus/application/running/RunningRecordServiceTest.java
- close #258 
- X
- 이번 주 날짜 응답의 형식을 `yyyy.MM.dd ~ MM.dd` 에서 `yyyy.MM.dd ~ yyyy.MM.dd`로 변경합니다.
- 요일 별 활동 값 응답을 double[] 에서 List<WeeklyRunningRatingDto>로 변경합니다.
- 요일 별 활동 값을 나타내는 `WeeklyRunningRatingDto`를 추가합니다.
-
=> Fix: 활동요약 응답 형식 변경

src/main/java/com/dnd/runus/presentation/v1/scale/dto/ScaleCoursesResponse.java
- close #262 
- x
- 기존에는 현재 달성한 거리를 미터 단위로 표현합니다.
- 1km 이상인 경우, 소수점 1자리인 km 단위로 수정합니다.
-
=> Fix: 1km 이상인 거리에 대해 현재 달성한 거리를 km 단위로 수정

src/main/java/com/dnd/runus/infrastructure/persistence/jpa/running/JpaRunningRecordRepository.java
- close #265 
- X
- 기존에는 러닝 기록 조회 시 마다 member 테이블을 다시 조회합니다. (N + 1 문제) 
- 이 PR에서는 `JpaRunningRecordRepository.findByMemberIdAndStartAtBetween()` 메서드에서 `member` 테이블을 fetch join하도록 수정합니다.
-
=> Fix: JpaRunningRecordRepository.findByMemberIdAndStartAtBetween 메서드에서 member 테이블을 fetch join하도록 수정

src/main/java/com/dnd/runus/global/exception/type/ErrorType.java, src/main/java/com/dnd/runus/presentation/handler/ExceptionRestHandler.java
- close #198 
- x
- 로깅 정보를 나타낼 ErrorType.Level enum 클래스를 추가합니다.
- 예외 발생 시, ErrorType에 해당하는 로그 레벨로 로깅합니다.
- 로깅 시, Exception 클래스 이름을 메세지와 함께 로깅하도록 합니다.
- `IllegalArgumentException` 예외 처리를 `ExceptionRestHandler`에 추가합니다.
-
=> Fix: ExceptionRestHandler 로깅을 ErrorType에 따른 레벨로 수정

src/main/java/com/dnd/runus/application/oauth/OauthService.java, src/main/java/com/dnd/runus/presentation/v1/oauth/OauthController.java, src/main/java/com/dnd/runus/presentation/v1/oauth/dto/response/WithdrawResponse.java
- close #269 
- `/api/v1/auth/oauth/withdraw` API에서 탈퇴 성공 여부에 따른 bool 값을 포함하여 반환하도록 수정합니다.
- 기존에는 비동기로 oidc 제공 서버로 revoke 요청합니다.
- `withDrawEvent`가 revoke 성공 여부와 상관없이 발생합니다.
- 이를 런어스 서버에서 oauth 서버로 revoke 요청을 보내고 기다렸다가 성공 여부를 클라이언트에게 반환하도록 합니다.
- `withDrawEvent`를 revoke가 성공했을 때만 발생시킵니다.
- `OauthService.revokeOauth()` 메서드에서 성공 여부에 따른 반환값을 추가합니다.
-
=> Fix: OauthService.revokeOauth()에서 oidc revoke 요청을 기다렸다가 성공 여부를 반환하도록 수정

.gitignore, build.gradle.kts, gradle/libs.versions.toml, src/main/resources/logback-spring.xml, src/main/resources/logback-variables.properties
- close #272 
- x
- 로그 파일 저장하기 위해 logback-spring.yml 파일을 추가합니다.
- 기존에는 로그를 출력하고 따로 저장하지 않습니다.
- 이 PR 작업으로 로그를 `logs` 경로 아래에 월별, 일별로 분리하여 로그를 저장합니다.
- 로그 파일 저장 경로인 `logs`는 gitignore 처리합니다.
- json 형태로 로그를 저장하기 위해 `logback-json-classic`, `logback-jackson` 의존성을 추가합니다.
- 이 작업 이후로 운영서버에 Loki, Promtail 설정해둘께요!
=> Feat: 로그 파일 저장 설정용  logback-spring.yml 추가

src/main/java/com/dnd/runus/application/badge/BadgeService.java, src/main/java/com/dnd/runus/domain/badge/BadgeWithAchieveStatusAndAchievedAt.java, src/main/java/com/dnd/runus/presentation/v1/badge/dto/response/AllBadgesListResponse.java, src/test/java/com/dnd/runus/application/badge/BadgeServiceTest.java
- close #274 
- X
- 뱃지 리스트 응답에 achievedAt(성취 날짜값을 추가합니다.)
- 사용자가 뱃지를 성취했으면 achievedAt에 성취한 날짜가, 아니면 null값을 리턴합니다.
- `BadgeWithAchievedStatus`하고 `BadgeWithAchieveStatusAndAchievedAt`부분을 합칠 수 있을 것 같은데 해당 부분은 시간되면 추후 리팩터링 하겠습니다.
=> Fix: 뱃지 리스트 조회 API 응답형식 변경

src/main/resources/logback-spring.xml
- x
- x
새로운 날짜 로그 파일에 기록하지 않는 버그를 수정합니다.
[AS-IS]
- `SizeAndTimeBasedRollingPolicy`를 사용합니다.
- 이로 인해 날짜가 바뀌더라도 최대 용량에 미치지 않았으므로, 기존의 로그 파일에 계속 기록합니다.
[TO-BE]
-  `TimeBasedRollingPolicy` 로그 정책으로 변경합니다.
- 날짜가 바뀌면 새로운 날짜에 해당하는 로그 파일을 생성합니다. 그리고 새로운 로그 파일에 기록합니다.
-
=> Fix: 날짜가 바뀌면 새로운 날짜 파일에 log를 기록하도록 수정

src/main/java/com/dnd/runus/application/member/MemberEventHandler.java, src/main/java/com/dnd/runus/application/member/MemberService.java, src/main/java/com/dnd/runus/application/member/MemberWithdrawService.java, src/main/java/com/dnd/runus/application/member/event/SignupEvent.java, src/main/java/com/dnd/runus/application/member/event/WithdrawEvent.java, src/main/java/com/dnd/runus/application/oauth/OauthService.java, src/main/java/com/dnd/runus/application/oauth/SocialProfileService.java, src/main/java/com/dnd/runus/infrastructure/persistence/jpa/member/JpaSocialProfileRepository.java, src/test/java/com/dnd/runus/application/oauth/OauthServiceTest.java
- close #275 
- x
- `OauthService`에서 socialProfile 생성 로직을 `SocialProfileService`로 분리합니다. https://github.com/dnd-side-project/dnd-11th-2-backend/commit/113698a7c66e2c29370422823e83778745b3de58
- `SignupEvent`, `WithdrawEvent`를 발생하도록 수정해 `MemberEventHandler` 컴포넌트에서 각각 처리하도록 합니다.
- 이후 `SignupEvent`가 발생하면 `BadgeEventHandler`에서 해당 멤버에게 배지를 부여하도록 고려중이에요
=> Refactor: OauthService 회원 가입, 로그인, 탈퇴 시 Oauth id token, access token 요청/응답과 db 트랜잭션 분리 

src/main/java/com/dnd/runus/infrastructure/persistence/jpa/badge/entity/BadgeAchievementEntity.java, src/main/resources/db/migration/V5.0.13__badge_achievement_unique.sql
- close #279 
- x
- 배지 달성 테이블에 유니크 키(`badge_id`, `member_id`)를 추가합니다.
-
=> Fix: badge_achievement 테이블에 unique key 추가

src/main/java/com/dnd/runus/domain/badge/BadgeAchievementRepository.java, src/main/java/com/dnd/runus/infrastructure/persistence/domain/badge/BadgeAchievementRepositoryImpl.java, src/main/java/com/dnd/runus/infrastructure/persistence/jooq/badge/JooqBadgeAchievementRepository.java, src/test/java/com/dnd/runus/infrastructure/persistence/domain/badge/BadgeAchievementRepositoryImplTest.java
- close #281 
- x
- 중복되는 배지 달성 row를 제외하고 새로운 row만 추가하는 레포지터리 함수를 jOOQ로 추가합니다.
- `onConflictDoNothing` 사용
-
=> Feat: badge_achievement 중복 무시하고 저장하는 함수 추가

src/main/java/com/dnd/runus/application/badge/BadgeEventHandler.java, src/main/java/com/dnd/runus/application/badge/BadgeService.java, src/main/java/com/dnd/runus/domain/badge/BadgeRepository.java, src/main/java/com/dnd/runus/infrastructure/persistence/domain/badge/BadgeRepositoryImpl.java, src/main/java/com/dnd/runus/infrastructure/persistence/jooq/badge/JooqBadgeAchievementRepository.java, src/main/java/com/dnd/runus/infrastructure/persistence/jpa/badge/JpaBadgeRepository.java
- close #45 
- x
- 회원가입 시, `BadgeType.PERSONAL_RECORD`이고 요구량이 0 이하인 `시작이 반이다` 뱃지를 부여합니다.
- 운영 디비에 현재 멤버들에 대해서 가입 시간에 맞게 해당 뱃지를 추가했어요!
```sql
INSERT INTO badge_achievement (badge_id, member_id, created_at, updated_at)
SELECT 
3, -- 회원가입 뱃지 id
m.id, 
m.created_at, 
NOW()
FROM 
member m;
```
=> Feat: 회원가입 뱃지 부여 기능 추가

src/main/java/com/dnd/runus/application/running/RunningRecordService.java, src/test/java/com/dnd/runus/application/running/RunningRecordServiceTest.java
- close #284 
- X
- 활동요약에서 저번주 평균값이 이번주 평균값으로 나오는 버그를 수정합니다.
- 평균 값 조회시 날짜 범위를 이번주에서 저번주로 수정합니다.
- X
=> Fix: 활동요약에서 저번주 평균값이 이번주 평균값으로 나오는 버그 수정

src/main/java/com/dnd/runus/application/badge/BadgeService.java, src/main/java/com/dnd/runus/domain/badge/BadgeAchievementRepository.java, src/main/java/com/dnd/runus/infrastructure/persistence/domain/badge/BadgeAchievementRepositoryImpl.java, src/main/java/com/dnd/runus/infrastructure/persistence/jooq/badge/JooqBadgeAchievementRepository.java, src/test/java/com/dnd/runus/application/badge/BadgeServiceTest.java, src/test/java/com/dnd/runus/infrastructure/persistence/domain/badge/BadgeAchievementRepositoryImplTest.java
- close #285 
- GET `/api/v1/badges/me`
- 나의 기록의 뱃지 리스트 조회 시, 획득한 날짜 최신 기준으로 최대 3개를 리턴하도록 변경합니다.
- 조회 쿼리를 최신 기준으로 order by후 3개만 조회하도록 변경합니다.
- BadgeAchievementRepository의 `findByMemberIdWithBadge`함수명을 좀 더 명확한 `findByMemberIdWithBadgeOrderByAchievedAtLimit`로 변경합니다. 
-
=> Fix: 나의 기록 뱃지 조회를 최신 기준으로 최대 3개 리턴하도록 수정

src/main/java/com/dnd/runus/application/badge/BadgeEventHandler.java, src/main/java/com/dnd/runus/application/member/MemberEventHandler.java, src/main/java/com/dnd/runus/application/member/MemberService.java, src/main/java/com/dnd/runus/application/running/RunningRecordService.java, src/main/java/com/dnd/runus/application/running/event/RunningRecordAddedEvent.java, src/main/java/com/dnd/runus/application/scale/ScaleEventHandler.java, src/main/java/com/dnd/runus/application/scale/ScaleService.java, src/main/java/com/dnd/runus/domain/running/RunningRecordRepository.java, src/main/java/com/dnd/runus/infrastructure/persistence/domain/running/RunningRecordRepositoryImpl.java, src/main/java/com/dnd/runus/infrastructure/persistence/jooq/running/JooqRunningRecordRepository.java, src/test/java/com/dnd/runus/application/running/RunningRecordServiceTest.java
- close #289 
- x
- 러닝 기록 추가 시, `RunningRecordAddedEvent` 이벤트를 발생하도록 변경합니다.
- `RunningRecordAddedEvent` 이벤트를 수신받는 Listener들을 추가합니다.
- `BadgeEventHandler`: 개인기록(첫 러닝), 거리, 시간에 따른 뱃지 부여
- `MemberEventHandler`: 러닝한 거리에 따라 레벨 경험치 추가
- `ScaleEventHandler`: 달성한 거리 목표들 추가
-
=> Feat: RunningRecordAddedEvent 이벤트를 수신하여 러닝 뱃지 부여 로직 추가

src/main/java/com/dnd/runus/application/challenge/ChallengeService.java, src/test/java/com/dnd/runus/application/challenge/ChallengeServiceTest.java
- #290 
- X
- 사용자의 어제의 러닝 기록 유무에 따라 챌린지 리스트를 다르게 조회합니다.
- 조회한 리스트를 오늘의 날짜(자정)의 값을 seed로 설정하고 리스트를 shuffle합니다.
- shuffle한 리스트의 인덱스가 0,1인 값을 리턴합니다.
- key 값으로 (날짜 + 어제 러닝 기록 유무)로해서 캐시사용하는 것 어떻게 생각하시나요? 자정에 캐시를 갱신하도록 하고, 사용자가 챌린지 값을 요청할 때 사용자가 어제 러닝 기록 유무만 확인하고 캐싱하는 것 어떻게 생각하시나요?? 굳이 캐싱이 필요할까 싶기도 하는데 재원님은 어떻게 생각하시나요?
- 만약 캐시를 적용하게 된다면 우선 해당 pr 머지하고, 적용하는 것으로 진행하면 좋을 것 같습니다.
- 그리고 지금은 챌린지 데이터가 적어서 Collections.shuffle을 사용했는데 추후 데이터가 늘어날 가능성이 적긴하지만, 데이터가 많아 진다면 성능 이슈가 발생할 것 같아서 추후 이 부분도 좀 고민해봐야 될 것 같아요!
=> Feat: 챌린지 랜덤 기능 구현

src/main/java/com/dnd/runus/application/member/MemberService.java, src/main/java/com/dnd/runus/presentation/v1/member/MemberProfileController.java, src/main/java/com/dnd/runus/presentation/v1/member/dto/response/MyProfileResponse.java, src/main/java/com/dnd/runus/presentation/v1/member/dto/response/MyProfileResponseV1.java, src/main/java/com/dnd/runus/presentation/v2/member/MemberProfileControllerV2.java, src/main/java/com/dnd/runus/presentation/v2/member/dto/response/MyProfileResponseV2.java, src/test/java/com/dnd/runus/application/member/MemberServiceTest.java
- close #295
- GET `/api/v2/members/profiles`
- 응답 버전 별 공통으로 값을 가공할 수 있게 `MyProfileResponse`의 필드 값을 변경합니다.
- MemberService의 `getMyProfile`메서드가  `MyProfileResponse`를 리턴하도록 합니다.
- 기존의  `MyProfileResponse`을  `MyProfileResponseV1`으로 변경합니다.
- `MyProfileResponseV1`에서 `MyProfileResponse`값을 변환할 수 있게 합니다.
- 퍼센테이지 값을 추가한 `MyProfileResponseV2`를 생성하고 `/api/v2/members/profiles` api를 추가합니다.
- 해당 구조를 어떻게 변경할지는 백엔드 스크럼 회의에서 정하고 도메인 별로 리팩터링 작업 들어가면  될 것 같아요!
- 우선 임시로 구성했습니다.
- 리팩터링 코드랑, 구현 코드랑 별도로 PR를 올려야했었는데, 해당 작업이 목요일까지 완료하기로 예정되어서 같이 올렸어요! 다음부터는 나눠서 올리겠습니다🙏
=> Feat: 나의 기록 조회 V2 작업(퍼센테이지 값 추가)

src/main/java/com/dnd/runus/application/running/RunningRecordService.java, src/main/java/com/dnd/runus/application/scale/ScaleService.java, src/main/java/com/dnd/runus/domain/running/RunningRecordRepository.java, src/main/java/com/dnd/runus/infrastructure/persistence/domain/running/RunningRecordRepositoryImpl.java, src/main/java/com/dnd/runus/infrastructure/persistence/jooq/running/JooqRunningRecordRepository.java, src/test/java/com/dnd/runus/application/running/RunningRecordServiceTest.java, src/test/java/com/dnd/runus/application/scale/ScaleServiceTest.java, src/test/java/com/dnd/runus/infrastructure/persistence/domain/running/RunningRecordRepositoryImplTest.java
- #294 
- 기간 안의 데이터를 조회하는 함수명을 하나로 통일 했습니다.
- 기존의 `ByDateRange`, `AndDateRange` 등 여러개로 나타나있던 접미사를 `WithDateRage`로 변경했습니다.
- 리파지토리의 함수 순서를 다음과 같이 변경했습니다.
- find -> update -> save -> delete 순, jpa -> jooq 순
- 날짜 관련 없이 사용자에 따라 전체 러닝 거리 합을 조회하는 함수가 여러 곳에서 사용해서 사용자 id에 따라  전체 러닝 거리 합을 조회하는 리파지토리 함수 `findTotalDistanceMeterByMemberId`를 추가했습니다.
- 기존에 사용자의 전체 러닝 거리를 조회하는 로직에서 `findTotalDistanceMeterByMemberIdWithRangeDate`를 `findTotalDistanceMeterByMemberId`로 변경했습니다.
- 사용자에 따라 전체 러닝 거리 합을 조회하는 함수가 여러 곳에서 필요할 것 같아서 따로 만들었는데 혹시 괜찮은가요?
- 리파지토리의 함수들이 늘어나면서 한번에 보기 힘들어 지는 것 같아요! 함수의 순서를 다음 백엔드 스크럼때 같이 정하면 좋을 것 같아요!
=> Refactor: 러닝 레코드 Repository 리팩터링

src/main/java/com/dnd/runus/application/running/RunningRecordService.java, src/main/java/com/dnd/runus/application/running/RunningRecordServiceV2.java, src/main/java/com/dnd/runus/presentation/v1/running/RunningRecordController.java, src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordMonthlySummaryResponse.java, src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordMonthlySummaryResponseV1.java, src/main/java/com/dnd/runus/presentation/v2/running/RunningRecordControllerV2.java, src/main/java/com/dnd/runus/presentation/v2/running/dto/response/RunningRecordMonthlySummaryResponseV2.java, src/test/java/com/dnd/runus/application/running/RunningRecordServiceTest.java
- close #294 
- #301 
- GET `api/v2/running-records/monthly-summary`
- 리팩터링 관련
- V1, V2 공통 리스펀스 DTO RunningRecordMonthlySummaryResponse로 지정합니다. 
- 공통으로 필요하는 month, monthlyTotalMeter 값을 서비스단의 `getMonthlyRunningSummery`함수에서 리턴하도록 변경합니다.
- V1에서 추가로 필요한 다음 레벨 값과 다음 레벨까지 남은 거리수를 구하기 위해 `MemberService`의 `getMyProfile` 메서드로 가져옵니다.
- 컨트롤러에서 위의 두개의 값을 가공해 RunningRecordMonthlySummaryResponseV1으로 리턴하도록 변경합니다.
- V2 추가
-  현재 사용자가 달리고 있는 지구 한 바퀴 코스를 조회하고, 코스에 대한 퍼센티지 값들을 계산해서 리턴하는 `getPercentageValues` 메서드를 `RunningRecordServiceV2.java`에 추가합니다.
- 패키지 위치나, DTO명은 임시로 지정했어요. 버전 관련해서 구조를 어떻게 변경할지 결정되어 리팩터링 작업 들어가면 그 때 다시 변경하도록 하겠습니다.
=> Feat: 이번달 러닝 서머리 V2 API 추가

src/main/java/com/dnd/runus/application/oauth/SocialProfileService.java, src/main/java/com/dnd/runus/global/exception/type/ErrorType.java, src/main/java/com/dnd/runus/presentation/v1/oauth/OauthController.java, src/test/java/com/dnd/runus/application/oauth/OauthServiceTest.java
- close #306 
- x
- oauth sign in 과정에서 해당 소셜 로그인 멤버를 찾지 못한 경우, 반환하는 에러 코드를 `OAUTH_001`로 변경합니다.
-
=> Fix: oauth 로그인 시 회원을 찾지 못한 경우에 반환하는 에러 타입을 변경

src/main/java/com/dnd/runus/application/oauth/OauthService.java, src/main/java/com/dnd/runus/application/oauth/SocialProfileService.java, src/main/java/com/dnd/runus/global/exception/type/ErrorType.java, src/main/java/com/dnd/runus/presentation/v1/oauth/OauthController.java
- close #306 
- x
- id token에 이메일 필드가 없는 경우, `FAILED_AUTHENTICATION`에서 `EMAIL_NOT_FOUND_IN_ID_TOKEN`을 반환하도록 수정합니다.
- BusinessException 대신 AuthException을 사용하도록 수정합니다.
-
=> Fix: oauth 로그인 시 id token에 이메일 필드가 없는 경우 에러 타입 변경

src/main/java/com/dnd/runus/application/scale/ScaleService.java, src/main/java/com/dnd/runus/application/scale/dto/CoursesDto.java, src/main/java/com/dnd/runus/presentation/v1/scale/ScaleController.java, src/main/java/com/dnd/runus/presentation/v1/scale/dto/ScaleCoursesResponse.java, src/test/java/com/dnd/runus/application/scale/ScaleServiceTest.java, src/test/java/com/dnd/runus/presentation/v1/scale/ScaleControllerTest.java
- #303 
- GET `/api/v1/scale/course`
- 달성 기록 API를 리팩터링 합니다.
- 서비스 단에서 전체 코스(달성한 코스 리스트, 현재 코스, 남은 코스 리스트)와 달성 정보(전체 코스, 전체 코스의 거리, 사용자가 달린 전체 거리)를 리턴할 수 있게 `getAchievements` 함수를 변경합니다.
- v1의 리스펀스 관련 데이터 가공을 Controller와 `ScaleCoursesResponse`에서 처리합니다.
- 현재 코스의 메세지 형태가 변경되어서 V1과 V2로 나누게 되었습니다.
- Controller와 ReponseDto를 적절히 구성했는지 잘 모르겠습니다. 혹시 좋은 의견 있으면 주세요!
- v1 리턴 형식이 맞는지 간단하게 컨트롤러 모킹해서 테스트를 추가했습니다.
- 리팩터링 하면서 형식이 잘못된 부분이 있는지 크로스 체크 부탁드려요! (제가 구현했던 부분이 아니고, 현재 서비스에 바로 반영되고 있는 API라서 꼼꼼히 확인 부탁드립니다 🙏 )
=> Refactor: 달성 기록 API v1 리팩터링

gradle/libs.versions.toml, src/test/java/com/dnd/runus/presentation/config/ControllerTestHelper.java, src/test/java/com/dnd/runus/presentation/v1/scale/ScaleControllerTest.java
- close #312 
- x
- 테스트 환경에서 security 의존성을 추가합니다.
- `ControllerTestHelper` 추상 클래스를 추가합니다.
- `ScaleControllerTest `에서 `@WebMvcTest`를 사용하도록 변경합니다.
- controller 계층 테스트 시, `ControllerTestHelper`를 상속받아 사용하시면 됩니다.
- `@BeforeEach`에서 `setUpMockMvc`를 호출해야 해요!
- `@WithMockUser` 어노테이션도 컨트롤러 테스트 클래스에 추가해야 해요
=> Fix: ScaleControllerTest에서 WebMvcTest를 사용하도록 변경

src/main/java/com/dnd/runus/domain/challenge/Challenge.java, src/main/java/com/dnd/runus/infrastructure/persistence/jooq/challenge/JooqChallengeAchievementRepository.java, src/main/java/com/dnd/runus/infrastructure/persistence/jooq/challenge/JooqChallengeRepository.java, src/main/java/com/dnd/runus/infrastructure/persistence/jpa/challenge/entity/ChallengeEntity.java, src/main/resources/db/migration/V5.0.14__add_challenge_is_active.sql, src/test/java/com/dnd/runus/application/challenge/ChallengeServiceTest.java, src/test/java/com/dnd/runus/application/running/RunningRecordServiceTest.java, src/test/java/com/dnd/runus/infrastructure/persistence/domain/challenge/ChallengeAchievementPercentageRepositoryImplTest.java, src/test/java/com/dnd/runus/infrastructure/persistence/domain/challenge/ChallengeAchievementRepositoryImplTest.java
- #310 
- X
- Challenge 테이블에 isActive(현재 사용하는 챌린지인지 나타내는 컬럼)을 추가합니다.
- 기존의 데이터는 isActive를 true로 set하고, 추후 데이터를 변경합니다.
-
=> Feat: Challenge 테이블에 isActive 컬럼 추가

src/main/java/com/dnd/runus/domain/challenge/ChallengeRepository.java, src/main/java/com/dnd/runus/infrastructure/persistence/domain/challenge/ChallengeRepositoryImpl.java, src/main/java/com/dnd/runus/infrastructure/persistence/jooq/challenge/JooqChallengeRepository.java
- #310 
- X
- 챌린지 목록을 조회하는 findAllActiveChallengesWithConditions() 함수를 추가합니다.
- 챌린지 성공 여부를 프런트에서 하기 위해 challenge 값 + 챌린지 성공 유무 확인 조건 값을 같이 조회합니다.
-
=> Feat: 챌린지 목록 조회 리파지토리 추가(업데이트를 위한 조건 값까지 함께 조회)

src/main/java/com/dnd/runus/application/challenge/ChallengeService.java, src/main/java/com/dnd/runus/domain/challenge/ChallengeRepository.java, src/main/java/com/dnd/runus/domain/challenge/GoalMetricType.java, src/main/java/com/dnd/runus/infrastructure/persistence/domain/challenge/ChallengeRepositoryImpl.java, src/main/java/com/dnd/runus/infrastructure/persistence/jooq/challenge/JooqChallengeRepository.java, src/main/java/com/dnd/runus/infrastructure/persistence/jpa/challenge/JpaChallengeRepository.java, src/main/java/com/dnd/runus/presentation/v1/challenge/ChallengeController.java, src/main/java/com/dnd/runus/presentation/v1/challenge/dto/response/ChallengesResponse.java, src/test/java/com/dnd/runus/application/challenge/ChallengeServiceTest.java, src/test/java/com/dnd/runus/presentation/v1/challenge/ChallengeControllerTest.java
- close #310 
-  /api/v1/challenges
- Response에 큰 변동 사항이 없어 기존 v1 API를 유지하고, 기존 ReponseDTO에 목표 값과 챌린지 타입 필드를 추가합니다.
- 기존의 service단의 getChallenges 메서드를 다음과 같이 수정합니다.
- AS-IS: 사용자의 어제의 러닝 기록이 있을 경우, `어제의~` 와 관련된 챌린지도 같이 조회해서 랜덤으로 2개 리턴
- TO-BE
- 사용자가 어제의 러닝 기록이 없을 경우, `어제의~` 와 관련된 챌린지를 제외
- 필터링한 챌린지에서 랜덤으로 2개 추출
- 랜덤 2개의 챌린지 중 `어제의~` 와 관련된 챌린지가 포합되었을 경우, 사용자의 어제의 러닝기록(첫번째로 조회되는)을 이용해서 챌린지 목표값 리턴할 수 있게 함
- 머지는 12시에서 새벽사이에 진행 할 예정입니다.
- DB에 페이스 관련 챌린지의 isActive 값을 false로 변경 완료했습니다.
=> Refactor: 챌린지 조회 시 챌린지 목표 값까지 같이 리턴할 수 있게 수정

src/main/java/com/dnd/runus/domain/challenge/ChallengeRepository.java, src/main/java/com/dnd/runus/infrastructure/persistence/domain/challenge/ChallengeRepositoryImpl.java, src/main/java/com/dnd/runus/infrastructure/persistence/jpa/challenge/JpaChallengeRepository.java
- #319 
- X
- 러닝 데이터 저장 시, 챌린지 모드일 경우, 해당 챌린지가 존재하는지 확인하는 확인할 수 있게 findById 리파지토리 추가합니다.
-
=> Feat: Challenge findById 리파지토리 추가

src/main/java/com/dnd/runus/application/running/RunningRecordService.java, src/main/java/com/dnd/runus/presentation/v1/running/RunningRecordController.java, src/main/java/com/dnd/runus/presentation/v1/running/dto/request/RunningRecordRequestV1.java, src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordAddResultResponseV1.java, src/test/java/com/dnd/runus/application/running/RunningRecordServiceTest.java
- #319 
- X
- 네이밍을 명확하게 하기 위해 RunningRecordAddResultResponse -> RunningRecordAddResultResponseV1 으로, RunningRecordRequest -> RunningRecordRequestV1으로 클래스명 변경
- V2 서비스 단 함수를 추가하기 위해 기존 addRunningRecord함수를 addRunningRecordV1으로 변경
- 서비스단 함수 순서 변경(get -> add -> private 순)
-
=> Refactor: 러닝 결과 추가 관련 함수 및 클래스 이름 변경(기존 V1)

src/main/java/com/dnd/runus/application/running/RunningRecordService.java, src/main/java/com/dnd/runus/application/running/dto/RunningResultDto.java, src/main/java/com/dnd/runus/domain/common/CoordinatePoint.java, src/main/java/com/dnd/runus/global/exception/type/ErrorType.java, src/main/java/com/dnd/runus/presentation/v2/running/RunningRecordControllerV2.java, src/main/java/com/dnd/runus/presentation/v2/running/dto/RouteDtoV2.java, src/main/java/com/dnd/runus/presentation/v2/running/dto/request/RunningRecordRequestV2.java, src/main/java/com/dnd/runus/presentation/v2/running/dto/response/RunningRecordResultResponseV2.java, src/test/java/com/dnd/runus/application/running/RunningRecordServiceTest.java, src/test/java/com/dnd/runus/presentation/v2/running/RunningRecordControllerV2Test.java
- close #319 
- POST /api/v2/running-records
- 러닝 결과를 저장하는 API v2를 추가합니다.
- 챌린지 및 목표 request 형식이 달라졌습니다.
- 러닝 경로를 저장합니다.
- 챌린지 및 목표 성취에 대한 저장 방식이 추후 변경될 가능성이 있습니다.
- 서비스단에서 가공되지 않은 러닝 결과 dto인 `RunningResultDto`를 추가했습니다. 러닝 결과 조회 시 해당 Dto를 사용할 예정입니다. 데이터 가공은 각 프레젠테이션 계층에서 진행됩니다.
- 현재 기획에서는 고도가 러닝 경로에 들어가지 않아, altitude의 기본 값을 0으로 지정했습니다.
- `com.dnd.runus.presentation.v1.running.dto.request`에 있는 RunningAchievementMode는 변경 가능성이 매우 작고, 다른 버전에서 공통으로 사용되며, 서비스 계층에서도 사용되어서 해당 클래스를 `com.dnd.runus.application.running.dto` 패키지로 옮겨서 사용하는 건 어떻게 생각하는지 궁금합니다.
- 현재 RunningAchievementMode를 패키지 경로로 명시해 둔 부분이 있는데 이 부분은 위의 사항이 결정되면 변경할 예정입니다.
- 해당 pr이 완료되고, 목표와 챌린지 형식을 통합하는 pr를 올릴 예정입니다.(#317 )
=> Feat: 러닝 결과 저장 V2 API 구현(러닝 경로 추가)

src/main/java/com/dnd/runus/presentation/v1/challenge/dto/response/ChallengesResponse.java
- X
- X
-  챌린지 조회 시 목표값이 기본 목표값으로 리턴되는 버그를 수정합니다.
-
=> Fix: 챌린지 목표값이 기본 목표값으로 리턴하는 오류 수정(비교값으로 리턴되어야됨)

src/main/java/com/dnd/runus/application/running/RunningRecordService.java, src/main/java/com/dnd/runus/application/running/dto/RunningResultDto.java, src/main/java/com/dnd/runus/global/exception/type/ErrorType.java, src/main/java/com/dnd/runus/presentation/v1/running/RunningRecordController.java, src/main/java/com/dnd/runus/presentation/v1/running/dto/ChallengeDto.java, src/main/java/com/dnd/runus/presentation/v1/running/dto/GoalResultDto.java, src/main/java/com/dnd/runus/presentation/v1/running/dto/response/RunningRecordQueryResponse.java, src/main/java/com/dnd/runus/presentation/v2/running/RunningRecordControllerV2.java, src/main/java/com/dnd/runus/presentation/v2/running/dto/AchievementResultDto.java, src/main/java/com/dnd/runus/presentation/v2/running/dto/RouteDtoV2.java, src/main/java/com/dnd/runus/presentation/v2/running/dto/request/RunningRecordRequestV2.java, src/main/java/com/dnd/runus/presentation/v2/running/dto/response/RunningRecordResultResponseV2.java, src/test/java/com/dnd/runus/application/running/RunningRecordServiceTest.java, src/test/java/com/dnd/runus/presentation/v2/running/RunningRecordControllerV2Test.java
- #317 
-  X
- 러닝 결과의 챌린지 및 목표 달성 관련해서 응답 형식을 통합했습니다.
- percentage값은 사용자가 퍼센티이지를 나타내지 못하는 기록을 조회 할 경우를 null를 리턴하도록 구성했습니다.
- RunningRecordServcie.java의 `calChallengeAchievementPercentage` 는 이후 러닝 기록 조회 시 재 사용할 예정입니다.
- 오늘 안에 챌린지 및 목표 DTO 통합이 완료 되어야 되어서 러닝 결과 조회 V2 API도 같은 PR에 올리게 되었습니다.
- 코드 리뷰하기에 시간이 부족하면, 오늘 먼저 머지 진행하고, 금요일 스크럼에서 이야기 나누는 건 어떠세요?
=> Feat: 챌린지 및 목표 응답 DTO 통합

src/main/java/com/dnd/runus/presentation/v2/running/RunningRecordControllerV2.java, src/main/java/com/dnd/runus/presentation/v2/running/dto/RouteDtoV2.java, src/main/java/com/dnd/runus/presentation/v2/running/dto/request/RunningRecordRequestV2.java
- #327 
- X
- 러닝 경로가 null이거나 빈 리스트 이면 (0,0,0)인 지점을 start, end값으로 기본 설정합니다.
- start, end 지점은 null이면 안됩니다.(List<CoordinatePoint> 가 짝수야함.)
- 해당 PR 프런트에서 테스트하기 위해서 임시로 설정했습니다.
- 회의 때 최소 경로 수가 정해 지면, 빈리스트 체크 대신 최소 경로 수보다 작으면  (0,0,0)으로 저장하게 변경합니다.
=> Fix: 러닝 경로가 빈 리스트일 경우 좌표를 0,0,0인 지점을 저장하게 수정
